## 서버 포트 설정
server:
  port: 8724
  
## 오라클 드라이버 설정
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
    username: C##PROJECT_CLEAN
    password: PROJECT_CLEAN
    hikari:
      auto-commit: false

  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
    properties:
      hibernate:
        '[format_sql]': true  

  logging:
    level:
      root: error
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
    
