-- "TBL_AUTHORITY"

INSERT
  INTO TBL_AUTHORITY
  (
  AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC
  )
  VALUES
  (
  1, 'ROLE_CLIENT', '고객'
  );



INSERT
  INTO TBL_AUTHORITY
  (
  AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC
  )
  VALUES
  (
  2, 'ROLE_MEMBER', '모든 사용자'
  );

INSERT
  INTO TBL_AUTHORITY
  (
  AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC
  )
  VALUES
  (
  3, 'ROLE_EMPLOYEE', '직원'
  );
  
INSERT
  INTO TBL_AUTHORITY
  (
  AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC
  )
  VALUES
  (
  4, 'ROLE_ADMIN', '모든 관리자'
  );  

INSERT
  INTO TBL_AUTHORITY
  (
  AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC
  )
  VALUES
  (
  5, 'ROLE_ADMIN_BOSS', '사장'
  );  


INSERT
  INTO TBL_AUTHORITY
  (
  AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC
  )
  VALUES
  (
  6, 'ROLE_ADMIN_SEC', '보안 담당자'
  );
  
INSERT
  INTO TBL_AUTHORITY
  (
  AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC
  )
  VALUES
  (
  7, 'ROLE_ADMIN_HR', '인사 담당자'
  );  

INSERT
  INTO TBL_AUTHORITY
  (
  AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC
  )
  VALUES
  (
  8, 'ROLE_ADMIN_FNC', '재정 담당자'
  );

INSERT
  INTO TBL_AUTHORITY
  (
  AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC
  )
  VALUES
  (
  9, 'ROLE_FAIL', '로그인 실패'
  );

Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (21,'파이크','22071821','0000',to_date('22/07/05','RR/MM/DD'),'F','010-1111-1132',null,null,0,0,null,'N','N',null,'Y','N','N',to_date('22/07/18','RR/MM/DD'),'N','32324234@naver.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (1,'일라클','202201','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',to_date('22/01/01','RR/MM/DD'),'F','010-1111-1111',to_date('22/01/01','RR/MM/DD'),to_date('22/06/01','RR/MM/DD'),1,15,to_date('22/06/01','RR/MM/DD'),'N','Y',to_date('22/01/01','RR/MM/DD'),'Y','Y','Y',to_date('22/01/01','RR/MM/DD'),'N','email2@google.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (2,'이라클','202202','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',to_date('22/01/02','RR/MM/DD'),'F','010-1111-1112',to_date('22/01/02','RR/MM/DD'),to_date('22/06/02','RR/MM/DD'),3,11,to_date('22/06/01','RR/MM/DD'),'N','Y',to_date('22/01/02','RR/MM/DD'),'Y','Y','Y',to_date('22/01/02','RR/MM/DD'),'N','email3@google.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (3,'삼라클','202203','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',to_date('22/01/03','RR/MM/DD'),'F','010-1111-1113',to_date('22/01/03','RR/MM/DD'),to_date('22/06/03','RR/MM/DD'),3,3,to_date('22/06/01','RR/MM/DD'),'N','Y',to_date('22/01/03','RR/MM/DD'),'Y','Y','Y',to_date('22/01/03','RR/MM/DD'),'N','email4@google.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (4,'사라클','202204','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',to_date('22/01/04','RR/MM/DD'),'F','010-1111-1114',to_date('22/01/04','RR/MM/DD'),to_date('22/06/04','RR/MM/DD'),2,2,to_date('22/06/01','RR/MM/DD'),'N','Y',to_date('22/01/04','RR/MM/DD'),'Y','Y','Y',to_date('22/01/04','RR/MM/DD'),'N','email5@google.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (5,'오라클','202205','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',to_date('22/01/05','RR/MM/DD'),'M','010-1111-1115',to_date('22/01/05','RR/MM/DD'),to_date('22/06/05','RR/MM/DD'),1,22,to_date('22/06/01','RR/MM/DD'),'N','Y',to_date('22/01/05','RR/MM/DD'),'Y','Y','Y',to_date('22/01/05','RR/MM/DD'),'N','email6@google.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (6,'육라클','202206','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',to_date('22/01/06','RR/MM/DD'),'M','010-1111-1116',to_date('22/01/06','RR/MM/DD'),to_date('22/06/06','RR/MM/DD'),5,14,to_date('22/06/01','RR/MM/DD'),'N','Y',to_date('22/01/06','RR/MM/DD'),'Y','Y','Y',to_date('22/01/06','RR/MM/DD'),'N','email7@google.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (7,'칠라클','202207','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlKPWD',to_date('22/01/07','RR/MM/DD'),'M','010-1111-1117',to_date('22/01/07','RR/MM/DD'),to_date('22/06/07','RR/MM/DD'),2,55,to_date('22/06/01','RR/MM/DD'),'N','Y',to_date('22/01/07','RR/MM/DD'),'Y','Y','Y',to_date('22/01/07','RR/MM/DD'),'N','email7@google.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (8,'팔라클','202208','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',to_date('22/01/08','RR/MM/DD'),'M','010-1111-1118',to_date('22/01/08','RR/MM/DD'),to_date('22/06/08','RR/MM/DD'),1,63,to_date('22/06/01','RR/MM/DD'),'N','Y',to_date('22/01/08','RR/MM/DD'),'Y','Y','Y',to_date('22/01/08','RR/MM/DD'),'N','email9@google.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (9,'구라클','202209','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',to_date('22/01/09','RR/MM/DD'),'F','010-1111-1119',to_date('22/01/09','RR/MM/DD'),to_date('22/06/09','RR/MM/DD'),3,41,to_date('22/06/01','RR/MM/DD'),'N','Y',to_date('22/01/09','RR/MM/DD'),'Y','Y','Y',to_date('22/01/09','RR/MM/DD'),'N','email10@google.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (10,'십라클','202210','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',to_date('22/01/10','RR/MM/DD'),'M','010-1111-1121',to_date('22/01/10','RR/MM/DD'),to_date('22/06/10','RR/MM/DD'),0,29,to_date('22/06/01','RR/MM/DD'),'N','Y',to_date('22/01/10','RR/MM/DD'),'Y','Y','Y',to_date('22/01/10','RR/MM/DD'),'N','email11@google.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (11,'유한조','202211','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',to_date('99/01/01','RR/MM/DD'),'M','010-1111-1122',to_date('22/01/11','RR/MM/DD'),null,2,99,to_date('22/06/01','RR/MM/DD'),'N','N',to_date('22/01/11','RR/MM/DD'),'Y','Y','Y',to_date('22/01/11','RR/MM/DD'),'N','email12@google.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (12,'유호준','202212','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',to_date('99/01/02','RR/MM/DD'),'M','010-1111-1123',to_date('22/01/12','RR/MM/DD'),null,2,2,to_date('22/06/01','RR/MM/DD'),'N','N',to_date('22/01/12','RR/MM/DD'),'Y','Y','Y',to_date('22/01/12','RR/MM/DD'),'N','email13@google.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (13,'이다영','202213','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',to_date('99/01/03','RR/MM/DD'),'F','010-1111-1124',to_date('22/01/13','RR/MM/DD'),null,3,3,to_date('22/06/01','RR/MM/DD'),'N','N',to_date('22/01/13','RR/MM/DD'),'Y','Y','Y',to_date('22/01/13','RR/MM/DD'),'N','email14@google.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (14,'이시원','202214','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',to_date('99/01/04','RR/MM/DD'),'F','010-1111-1125',to_date('22/01/14','RR/MM/DD'),null,5,4,to_date('22/06/01','RR/MM/DD'),'Y','N',to_date('22/01/14','RR/MM/DD'),'Y','Y','Y',to_date('22/01/14','RR/MM/DD'),'N','email15@google.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (15,'나큰솔','202215','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',to_date('99/01/05','RR/MM/DD'),'M','010-1111-1126',to_date('22/01/15','RR/MM/DD'),null,0,5,to_date('22/06/01','RR/MM/DD'),'N','N',to_date('22/01/15','RR/MM/DD'),'Y','Y','Y',to_date('22/01/15','RR/MM/DD'),'N','email16@google.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (16,'서보라','202216','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',to_date('99/01/06','RR/MM/DD'),'F','010-1111-1127',to_date('22/01/16','RR/MM/DD'),null,2,11,to_date('22/06/01','RR/MM/DD'),'N','N',to_date('22/01/16','RR/MM/DD'),'Y','Y','Y',to_date('22/01/16','RR/MM/DD'),'N','email17@google.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (17,'이한조','202217','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',to_date('99/01/07','RR/MM/DD'),'M','010-1111-1128',to_date('22/01/17','RR/MM/DD'),null,0,6,to_date('22/06/01','RR/MM/DD'),'N','N',to_date('22/01/17','RR/MM/DD'),'Y','Y','Y',to_date('22/01/17','RR/MM/DD'),'N','email18@google.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (18,'김한조','202218','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',to_date('99/01/08','RR/MM/DD'),'M','010-1111-1129',to_date('22/01/18','RR/MM/DD'),null,5,7,to_date('22/06/01','RR/MM/DD'),'Y','N',to_date('22/01/18','RR/MM/DD'),'Y','N','N',to_date('22/01/18','RR/MM/DD'),'Y','email19@google.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (19,'박한조','202219','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',to_date('99/01/09','RR/MM/DD'),'F','010-1111-1130',to_date('22/01/19','RR/MM/DD'),null,0,8,to_date('22/06/01','RR/MM/DD'),'N','N',to_date('22/01/19','RR/MM/DD'),'Y','N','N',to_date('22/01/19','RR/MM/DD'),'Y','email20@google.com','11111@기본주소@상세주소1',null,null,null);
Insert into C##PROJECT_CLEAN.TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (20,'최한조','202220','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',to_date('99/01/10','RR/MM/DD'),'F','010-1111-1131',to_date('22/01/20','RR/MM/DD'),null,0,9,to_date('22/06/01','RR/MM/DD'),'N','N',to_date('22/01/20','RR/MM/DD'),'Y','N','N',to_date('22/01/20','RR/MM/DD'),'Y','email21@google.com','11111@기본주소@상세주소1',null,null,null);
-- "TBL_RESERVATION_INFO";
INSERT INTO TBL_RESERVATION_INFO
(
  RESERVATION_NO, USER_NAME, USER_PHONE_NO, USER_POSTAL_NO, USER_ADDRESS
, USER_DETAIL_ADDRESS, USER_HOUSE_SIZE, USER_RESERVATION_DATE, USER_REQUIREMENTS, BUSINESS_DATE
, BUSINESS_START_TIME, BUSINESS_END_TIME, BUSINESS_FIXED_PEOPLE, BUSINESS_APPLY_PEOPLE, TOTAL_PAYMENT
, APPLY_END_YN, RESERVATION_CANCEL_YN, PAYMENT_YN, GASHOOD_CLEAN_YN, MOLD_CLEAN_YN
, FILTER_CLEAN_YN, WAREHOUSE_CLEAN_YN, PET_YN, MULTIPLE_LAYER_YN
)
VALUES
(
  SEQ_TBL_RESERVATION.NEXTVAL, '유호준', '01012345678', 04916, '서울시 광진구 중곡1동'
, '63빌딩 3107호', 11, SYSDATE, '구석구석 깔끔하게 부탁드립니다', TO_DATE('22-07-27', 'YY-MM-DD')
, TO_DATE('2022-07-27 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-07-27 13:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 1, 54000
, 'Y', 'N', 'Y', 'N', 'N'
, 'N', 'N', 'N', 'Y'
);
INSERT INTO TBL_RESERVATION_INFO
(
  RESERVATION_NO, USER_NAME, USER_PHONE_NO, USER_POSTAL_NO, USER_ADDRESS
, USER_DETAIL_ADDRESS, USER_HOUSE_SIZE, USER_RESERVATION_DATE, USER_REQUIREMENTS, BUSINESS_DATE
, BUSINESS_START_TIME, BUSINESS_END_TIME, BUSINESS_FIXED_PEOPLE, BUSINESS_APPLY_PEOPLE, TOTAL_PAYMENT
, APPLY_END_YN, RESERVATION_CANCEL_YN, PAYMENT_YN, GASHOOD_CLEAN_YN, MOLD_CLEAN_YN
, FILTER_CLEAN_YN, WAREHOUSE_CLEAN_YN, PET_YN, MULTIPLE_LAYER_YN
)
VALUES
(
  SEQ_TBL_RESERVATION.NEXTVAL, '유한조', '01074152234', 25523, '서울시 종로구 인사1동'
, '덕진빌딩 3301호', 8, SYSDATE, '화장실 청소 위주로 부탁드립니다.', TO_DATE('22-07-27', 'YY-MM-DD')
, TO_DATE('2022-07-27 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-07-27 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 1, 33000
, 'Y', 'N', 'Y', 'N', 'N'
, 'N', 'N', 'N', 'Y'
);
INSERT INTO TBL_RESERVATION_INFO
(
  RESERVATION_NO, USER_NAME, USER_PHONE_NO, USER_POSTAL_NO, USER_ADDRESS
, USER_DETAIL_ADDRESS, USER_HOUSE_SIZE, USER_RESERVATION_DATE, USER_REQUIREMENTS, BUSINESS_DATE
, BUSINESS_START_TIME, BUSINESS_END_TIME, BUSINESS_FIXED_PEOPLE, BUSINESS_APPLY_PEOPLE, TOTAL_PAYMENT
, APPLY_END_YN, RESERVATION_CANCEL_YN, PAYMENT_YN, GASHOOD_CLEAN_YN, MOLD_CLEAN_YN
, FILTER_CLEAN_YN, WAREHOUSE_CLEAN_YN, PET_YN, MULTIPLE_LAYER_YN
)
VALUES
(
  SEQ_TBL_RESERVATION.NEXTVAL, '이시원', '01055554123', 14407, '서울시 송파구 잠실2동'
, '월드타워 7301호', 20, SYSDATE, '고양이 키웁니다~', TO_DATE('22-07-27', 'YY-MM-DD')
, TO_DATE('2022-07-27 12:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-07-27 16:30:00', 'YYYY-MM-DD HH24:MI:SS'), 2, 2, 85000
, 'Y', 'N', 'Y', 'N', 'N'
, 'N', 'N', 'N', 'Y'
);
INSERT INTO TBL_RESERVATION_INFO
(
  RESERVATION_NO, USER_NAME, USER_PHONE_NO, USER_POSTAL_NO, USER_ADDRESS
, USER_DETAIL_ADDRESS, USER_HOUSE_SIZE, USER_RESERVATION_DATE, USER_REQUIREMENTS, BUSINESS_DATE
, BUSINESS_START_TIME, BUSINESS_END_TIME, BUSINESS_FIXED_PEOPLE, BUSINESS_APPLY_PEOPLE, TOTAL_PAYMENT
, APPLY_END_YN, RESERVATION_CANCEL_YN, PAYMENT_YN, GASHOOD_CLEAN_YN, MOLD_CLEAN_YN
, FILTER_CLEAN_YN, WAREHOUSE_CLEAN_YN, PET_YN, MULTIPLE_LAYER_YN
)
VALUES
(
  SEQ_TBL_RESERVATION.NEXTVAL, '나큰솔', '01055554123', 99452, '경기도 구리시 토평1동'
, '160-13호 2층', 9, SYSDATE, '없습니다.', TO_DATE('22-07-27', 'YY-MM-DD')
, TO_DATE('2022-07-27 09:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-07-27 11:30:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 1, 33000
, 'Y', 'N', 'Y', 'N', 'N'
, 'N', 'N', 'N', 'Y'
);
INSERT INTO TBL_RESERVATION_INFO
(
  RESERVATION_NO, USER_NAME, USER_PHONE_NO, USER_POSTAL_NO, USER_ADDRESS
, USER_DETAIL_ADDRESS, USER_HOUSE_SIZE, USER_RESERVATION_DATE, USER_REQUIREMENTS, BUSINESS_DATE
, BUSINESS_START_TIME, BUSINESS_END_TIME, BUSINESS_FIXED_PEOPLE, BUSINESS_APPLY_PEOPLE, TOTAL_PAYMENT
, APPLY_END_YN, RESERVATION_CANCEL_YN, PAYMENT_YN, GASHOOD_CLEAN_YN, MOLD_CLEAN_YN
, FILTER_CLEAN_YN, WAREHOUSE_CLEAN_YN, PET_YN, MULTIPLE_LAYER_YN
)
VALUES
(
  SEQ_TBL_RESERVATION.NEXTVAL, '서보라', '01012348888', 83467, '서울시 중랑구 면목동'
, '160-77호 4층', 11, SYSDATE, '주방청소 위주로 부탁드려요~~.', TO_DATE('22-07-27', 'YY-MM-DD')
, TO_DATE('2022-07-27 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_timestamp('2022-07-27 17:30:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 1, 54000
, 'Y', 'N', 'Y', 'N', 'N'
, 'N', 'N', 'N', 'Y'
);
INSERT INTO TBL_RESERVATION_INFO
(
  RESERVATION_NO, USER_NAME, USER_PHONE_NO, USER_POSTAL_NO, USER_ADDRESS
, USER_DETAIL_ADDRESS, USER_HOUSE_SIZE, USER_RESERVATION_DATE, USER_REQUIREMENTS, BUSINESS_DATE
, BUSINESS_START_TIME, BUSINESS_END_TIME, BUSINESS_FIXED_PEOPLE, BUSINESS_APPLY_PEOPLE, TOTAL_PAYMENT
, APPLY_END_YN, RESERVATION_CANCEL_YN, PAYMENT_YN, GASHOOD_CLEAN_YN, MOLD_CLEAN_YN
, FILTER_CLEAN_YN, WAREHOUSE_CLEAN_YN, PET_YN, MULTIPLE_LAYER_YN
)
VALUES
(
  SEQ_TBL_RESERVATION.NEXTVAL, '이다영', '01042422424', 17845, '경기도 파주시 운양동'
, '111-11호 1층', 8, SYSDATE, '없어요~~.', TO_DATE('22-07-27', 'YY-MM-DD')
, TO_DATE('2022-07-27 17:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_timestamp('2022-07-27 19:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 1, 33000
, 'Y', 'N', 'Y', 'N', 'N'
, 'N', 'N', 'N', 'Y'
);

INSERT INTO TBL_RESERVATION_INFO
(
  RESERVATION_NO, USER_NAME, USER_PHONE_NO, USER_POSTAL_NO, USER_ADDRESS
, USER_DETAIL_ADDRESS, USER_HOUSE_SIZE, USER_RESERVATION_DATE, USER_REQUIREMENTS, BUSINESS_DATE
, BUSINESS_START_TIME, BUSINESS_END_TIME, BUSINESS_FIXED_PEOPLE, BUSINESS_APPLY_PEOPLE, TOTAL_PAYMENT
, APPLY_END_YN, RESERVATION_CANCEL_YN, PAYMENT_YN, GASHOOD_CLEAN_YN, MOLD_CLEAN_YN
, FILTER_CLEAN_YN, WAREHOUSE_CLEAN_YN, PET_YN, MULTIPLE_LAYER_YN
)
VALUES
(
  SEQ_TBL_RESERVATION.NEXTVAL, '유호준', '01012345678', 04916, '서울시 광진구 중곡1동'
, '63빌딩 3107호', 11, SYSDATE, '구석구석 깔끔하게 부탁드립니다', TO_DATE('22-07-29', 'YY-MM-DD')
, TO_DATE('2022-07-29 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-07-29 13:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, 54000
, 'N', 'N', 'Y', 'N', 'N'
, 'N', 'N', 'N', 'Y'
);
INSERT INTO TBL_RESERVATION_INFO
(
  RESERVATION_NO, USER_NAME, USER_PHONE_NO, USER_POSTAL_NO, USER_ADDRESS
, USER_DETAIL_ADDRESS, USER_HOUSE_SIZE, USER_RESERVATION_DATE, USER_REQUIREMENTS, BUSINESS_DATE
, BUSINESS_START_TIME, BUSINESS_END_TIME, BUSINESS_FIXED_PEOPLE, BUSINESS_APPLY_PEOPLE, TOTAL_PAYMENT
, APPLY_END_YN, RESERVATION_CANCEL_YN, PAYMENT_YN, GASHOOD_CLEAN_YN, MOLD_CLEAN_YN
, FILTER_CLEAN_YN, WAREHOUSE_CLEAN_YN, PET_YN, MULTIPLE_LAYER_YN
)
VALUES
(
  SEQ_TBL_RESERVATION.NEXTVAL, '유한조', '01074152234', 25523, '서울시 종로구 인사1동'
, '덕진빌딩 3301호', 8, SYSDATE, '화장실 청소 위주로 부탁드립니다.', TO_DATE('22-07-29', 'YY-MM-DD')
, TO_DATE('2022-07-29 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-07-29 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, 33000
, 'N', 'N', 'Y', 'N', 'N'
, 'N', 'N', 'N', 'Y'
);
INSERT INTO TBL_RESERVATION_INFO
(
  RESERVATION_NO, USER_NAME, USER_PHONE_NO, USER_POSTAL_NO, USER_ADDRESS
, USER_DETAIL_ADDRESS, USER_HOUSE_SIZE, USER_RESERVATION_DATE, USER_REQUIREMENTS, BUSINESS_DATE
, BUSINESS_START_TIME, BUSINESS_END_TIME, BUSINESS_FIXED_PEOPLE, BUSINESS_APPLY_PEOPLE, TOTAL_PAYMENT
, APPLY_END_YN, RESERVATION_CANCEL_YN, PAYMENT_YN, GASHOOD_CLEAN_YN, MOLD_CLEAN_YN
, FILTER_CLEAN_YN, WAREHOUSE_CLEAN_YN, PET_YN, MULTIPLE_LAYER_YN
)
VALUES
(
  SEQ_TBL_RESERVATION.NEXTVAL, '이시원', '01055554123', 14407, '서울시 송파구 잠실2동'
, '월드타워 7301호', 20, SYSDATE, '고양이 키웁니다~', TO_DATE('22-07-29', 'YY-MM-DD')
, TO_DATE('2022-07-29 12:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-07-29 16:30:00', 'YYYY-MM-DD HH24:MI:SS'), 2, 0, 85000
, 'N', 'N', 'Y', 'N', 'N'
, 'N', 'N', 'N', 'Y'
);
INSERT INTO TBL_RESERVATION_INFO
(
  RESERVATION_NO, USER_NAME, USER_PHONE_NO, USER_POSTAL_NO, USER_ADDRESS
, USER_DETAIL_ADDRESS, USER_HOUSE_SIZE, USER_RESERVATION_DATE, USER_REQUIREMENTS, BUSINESS_DATE
, BUSINESS_START_TIME, BUSINESS_END_TIME, BUSINESS_FIXED_PEOPLE, BUSINESS_APPLY_PEOPLE, TOTAL_PAYMENT
, APPLY_END_YN, RESERVATION_CANCEL_YN, PAYMENT_YN, GASHOOD_CLEAN_YN, MOLD_CLEAN_YN
, FILTER_CLEAN_YN, WAREHOUSE_CLEAN_YN, PET_YN, MULTIPLE_LAYER_YN
)
VALUES
(
  SEQ_TBL_RESERVATION.NEXTVAL, '나큰솔', '01055554123', 07777, '경기도 구리시 토평1동'
, '160-13호 2층', 9, SYSDATE, '없습니다.', TO_DATE('22-07-29', 'YY-MM-DD')
, TO_DATE('2022-07-29 09:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-07-29 11:30:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, 33000
, 'N', 'N', 'Y', 'N', 'N'
, 'N', 'N', 'N', 'Y'
);
INSERT INTO TBL_RESERVATION_INFO
(
  RESERVATION_NO, USER_NAME, USER_PHONE_NO, USER_POSTAL_NO, USER_ADDRESS
, USER_DETAIL_ADDRESS, USER_HOUSE_SIZE, USER_RESERVATION_DATE, USER_REQUIREMENTS, BUSINESS_DATE
, BUSINESS_START_TIME, BUSINESS_END_TIME, BUSINESS_FIXED_PEOPLE, BUSINESS_APPLY_PEOPLE, TOTAL_PAYMENT
, APPLY_END_YN, RESERVATION_CANCEL_YN, PAYMENT_YN, GASHOOD_CLEAN_YN, MOLD_CLEAN_YN
, FILTER_CLEAN_YN, WAREHOUSE_CLEAN_YN, PET_YN, MULTIPLE_LAYER_YN
)
VALUES
(
  SEQ_TBL_RESERVATION.NEXTVAL, '서보라', '01012348888', 13467, '서울시 중랑구 면목동'
, '160-77호 4층', 11, SYSDATE, '주방청소 위주로 부탁드려요~~.', TO_DATE('22-07-29', 'YY-MM-DD')
, TO_DATE('2022-07-29 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_timestamp('2022-07-29 17:30:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, 54000
, 'N', 'N', 'Y', 'N', 'N'
, 'N', 'N', 'N', 'Y'
);
INSERT INTO TBL_RESERVATION_INFO
(
  RESERVATION_NO, USER_NAME, USER_PHONE_NO, USER_POSTAL_NO, USER_ADDRESS
, USER_DETAIL_ADDRESS, USER_HOUSE_SIZE, USER_RESERVATION_DATE, USER_REQUIREMENTS, BUSINESS_DATE
, BUSINESS_START_TIME, BUSINESS_END_TIME, BUSINESS_FIXED_PEOPLE, BUSINESS_APPLY_PEOPLE, TOTAL_PAYMENT
, APPLY_END_YN, RESERVATION_CANCEL_YN, PAYMENT_YN, GASHOOD_CLEAN_YN, MOLD_CLEAN_YN
, FILTER_CLEAN_YN, WAREHOUSE_CLEAN_YN, PET_YN, MULTIPLE_LAYER_YN)
VALUES
(
  SEQ_TBL_RESERVATION.NEXTVAL, '이다영', '01042422424', 14368, '경기도 파주시 운양동'
, '111-11호 1층', 8, SYSDATE, '없어요~~.', TO_DATE('22-07-29', 'YY-MM-DD')
, TO_DATE('2022-07-29 17:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_timestamp('2022-07-29 19:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, 33000
, 'N', 'N', 'Y', 'N', 'N'
, 'N', 'N', 'N', 'Y'
);


-- "TBL_ADMIN";

INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL,'이시원','cleanup'||TO_CHAR(SYSDATE, 'YYMMDD')
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('98/02/18','RR/MM/DD'),'F'
, '010-11111-1111', TO_DATE('22/07/05','RR/MM/DD'), NULL
, 'N','총관리자', TO_DATE('22/07/05','RR/MM/DD')
, 20000000, 3, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);
INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL, '서보라', 'cleanup210823'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('94/04/27','RR/MM/DD'), 'F'
, '010-2222-2222', TO_DATE('21/08/23','RR/MM/DD'), NULL
, 'N', '인사관리자', TO_DATE('22/07/05','RR/MM/DD')
, 2300000, 1, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);

INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL,'이유미', 'cleanup200304'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('92/08/06','RR/MM/DD'), 'F'
, '010-3333-3333', TO_DATE('20/03/04','RR/MM/DD'), TO_DATE('22/07/03','RR/MM/DD')
, 'Y', '인사관리자', TO_DATE('22/07/03','RR/MM/DD')
, 3400000, 5, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);

INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL, '신순록', 'cleanup210627'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('94/07/06','RR/MM/DD'), 'M'
, '01044444444', TO_DATE('22/06/27','RR/MM/DD'), NULL
, 'N', '일반관리자', TO_DATE('22/07/05','RR/MM/DD')
, 2500000, 2, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);

INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL, '조완', 'cleanup210728'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('96/04/09','RR/MM/DD'), 'M'
, '010-5555-5555', TO_DATE('21/07/28','RR/MM/DD'), NULL
, 'N', '재정담당자', TO_DATE('22/07/04','RR/MM/DD')
, 4300000, 6, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);

INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL, '이은조', 'cleanup210607'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('95/10/18','RR/MM/DD'), 'F'
, '010-6666-6666', TO_DATE('21/06/07','RR/MM/DD'), TO_DATE('22/07/02','RR/MM/DD')
, 'Y', '보안담당자', TO_DATE('22/07/01','RR/MM/DD')
, 3200000, 7, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);

INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL, '조아영', 'cleanup220613'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('97/11/13','RR/MM/DD'), 'F'
, '010-7777-7777', TO_DATE('22/06/13','RR/MM/DD'), NULL
, 'N', '보안담당자', TO_DATE('22/07/05','RR/MM/DD')
, 1800000, 0, 'toothcoool@gmail.com'
, '333$경기도 안양시 만안구 안양로$안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);


INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL, '이다영', 'cleanup210628'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('94/07/06','RR/MM/DD'), 'M'
, '010-8888-8888', TO_DATE('22/06/27','RR/MM/DD'), NULL
, 'N', '일반관리자', TO_DATE('22/07/05','RR/MM/DD')
, 2500000, 2, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);

INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL, '유호준', 'cleanup210729'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('96/04/09','RR/MM/DD'), 'M'
, '010-9999-9999', TO_DATE('21/07/28','RR/MM/DD'), NULL
, 'N', '재정담당자', TO_DATE('22/07/04','RR/MM/DD')
, 4300000, 6, 'toothcoool@gmail.com'
, '333$경기도 안양시 만안구 안양로$안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);

INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL, '유한조', 'cleanup210608'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('95/10/18','RR/MM/DD'), 'F'
, '01011112222', TO_DATE('21/06/07','RR/MM/DD'), TO_DATE('22/07/02','RR/MM/DD')
, 'Y', '보안담당자', TO_DATE('22/07/01','RR/MM/DD')
, 3200000, 7, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);

INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL, '나큰솔', 'cleanup220616'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('97/11/13','RR/MM/DD'), 'F'
, '010-1111-3333', TO_DATE('22/06/13','RR/MM/DD'), NULL
, 'N', '보안담당자', TO_DATE('22/07/05','RR/MM/DD')
, 1800000, 0, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);

-- "TBL_RETIRE_EMPLOYEE"; 
INSERT 
  INTO TBL_RETIRE_EMPLOYEE 
  (
   RETIRE_EMPLOYEE_NO, EMPLOYEE_NAME, RETIRE_EMPLOYEE_ID, RETIRE_EMPLOYEE_PWD, RETIRE_EMPLOYEE_BIRTH, 
   RETIRE_EMPLOYEE_GENDER, RETIRE_EMPLOYEE_PHONE, RETIRE_EMPLOYEE_HIRE_DATE, RETIRE_EMPLOYEE_RETIRE_DATE,
   RETIRE_EMPLOYEE_SUM_COUNT, RETIRE_EMPLOYEE_SUM_TIME, RETIRE_EMPLOYEE_EMAIL, RETIRE_EMPLOYEE_RETIRE_YN, EMPLOYEE_LAST_LOGIN_DATE
   ) 
   VALUES 
   (
   SEQ_EMP_RET_NO.NEXTVAL, '일라클', '202201', '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('22/01/01','RR/MM/DD'), 
   'F', '01001111111', TO_DATE('22/01/01','RR/MM/DD'), TO_DATE('22/06/01','RR/MM/DD'),
   1, 15, 'email1', 'Y', TO_DATE('22/06/01','RR/MM/DD')
   );

INSERT 
  INTO TBL_RETIRE_EMPLOYEE 
  (
   RETIRE_EMPLOYEE_NO, EMPLOYEE_NAME, RETIRE_EMPLOYEE_ID, RETIRE_EMPLOYEE_PWD, RETIRE_EMPLOYEE_BIRTH, 
   RETIRE_EMPLOYEE_GENDER, RETIRE_EMPLOYEE_PHONE, RETIRE_EMPLOYEE_HIRE_DATE, RETIRE_EMPLOYEE_RETIRE_DATE,
   RETIRE_EMPLOYEE_SUM_COUNT, RETIRE_EMPLOYEE_SUM_TIME, RETIRE_EMPLOYEE_EMAIL, RETIRE_EMPLOYEE_RETIRE_YN, EMPLOYEE_LAST_LOGIN_DATE
   ) 
   VALUES 
   (
   SEQ_EMP_RET_NO.NEXTVAL, '이라클', '202202', '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('22/01/02','RR/MM/DD'), 
   'F', '01002222222', TO_DATE('22/01/02','RR/MM/DD'), TO_DATE('22/06/02','RR/MM/DD'),
   3, 11, 'email2', 'Y', TO_DATE('22/06/02','RR/MM/DD')
   );

INSERT 
  INTO TBL_RETIRE_EMPLOYEE 
  (
   RETIRE_EMPLOYEE_NO, EMPLOYEE_NAME, RETIRE_EMPLOYEE_ID, RETIRE_EMPLOYEE_PWD, RETIRE_EMPLOYEE_BIRTH, 
   RETIRE_EMPLOYEE_GENDER, RETIRE_EMPLOYEE_PHONE, RETIRE_EMPLOYEE_HIRE_DATE, RETIRE_EMPLOYEE_RETIRE_DATE,
   RETIRE_EMPLOYEE_SUM_COUNT, RETIRE_EMPLOYEE_SUM_TIME, RETIRE_EMPLOYEE_EMAIL, RETIRE_EMPLOYEE_RETIRE_YN, EMPLOYEE_LAST_LOGIN_DATE
   ) 
   VALUES 
   (
   SEQ_EMP_RET_NO.NEXTVAL, '삼라클', '202203', '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('22/01/03','RR/MM/DD'), 
   'F', '01003333333', TO_DATE('22/01/03','RR/MM/DD'), TO_DATE('22/06/03','RR/MM/DD'),
   3, 3,'email3','Y',TO_DATE('22/06/03','RR/MM/DD'))
   ;

INSERT 
  INTO TBL_RETIRE_EMPLOYEE 
  (
   RETIRE_EMPLOYEE_NO, EMPLOYEE_NAME, RETIRE_EMPLOYEE_ID, RETIRE_EMPLOYEE_PWD, RETIRE_EMPLOYEE_BIRTH, 
   RETIRE_EMPLOYEE_GENDER, RETIRE_EMPLOYEE_PHONE, RETIRE_EMPLOYEE_HIRE_DATE, RETIRE_EMPLOYEE_RETIRE_DATE,
   RETIRE_EMPLOYEE_SUM_COUNT, RETIRE_EMPLOYEE_SUM_TIME, RETIRE_EMPLOYEE_EMAIL, RETIRE_EMPLOYEE_RETIRE_YN, EMPLOYEE_LAST_LOGIN_DATE
   ) 
   VALUES 
   (
   SEQ_EMP_RET_NO.NEXTVAL, '사라클', '202204', '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('22/01/04','RR/MM/DD'), 
   'F', '01004444444', TO_DATE('22/01/04','RR/MM/DD'), TO_DATE('22/06/04','RR/MM/DD'),
   2, 2,'email4','Y',TO_DATE('22/06/04','RR/MM/DD'))
   ;

INSERT 
  INTO TBL_RETIRE_EMPLOYEE 
  (
   RETIRE_EMPLOYEE_NO, EMPLOYEE_NAME, RETIRE_EMPLOYEE_ID, RETIRE_EMPLOYEE_PWD, RETIRE_EMPLOYEE_BIRTH, 
   RETIRE_EMPLOYEE_GENDER, RETIRE_EMPLOYEE_PHONE, RETIRE_EMPLOYEE_HIRE_DATE, RETIRE_EMPLOYEE_RETIRE_DATE,
   RETIRE_EMPLOYEE_SUM_COUNT, RETIRE_EMPLOYEE_SUM_TIME, RETIRE_EMPLOYEE_EMAIL, RETIRE_EMPLOYEE_RETIRE_YN, EMPLOYEE_LAST_LOGIN_DATE
   ) 
   VALUES 
   (
   SEQ_EMP_RET_NO.NEXTVAL, '오라클', '202205', '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('22/01/05','RR/MM/DD'), 
   'M', '01005555555', TO_DATE('22/01/05','RR/MM/DD'), TO_DATE('22/06/05','RR/MM/DD'),
   1, 22, 'email5', 'Y', TO_DATE('22/06/05','RR/MM/DD')
   );

INSERT 
  INTO TBL_RETIRE_EMPLOYEE 
  (
   RETIRE_EMPLOYEE_NO, EMPLOYEE_NAME, RETIRE_EMPLOYEE_ID, RETIRE_EMPLOYEE_PWD, RETIRE_EMPLOYEE_BIRTH, 
   RETIRE_EMPLOYEE_GENDER, RETIRE_EMPLOYEE_PHONE, RETIRE_EMPLOYEE_HIRE_DATE, RETIRE_EMPLOYEE_RETIRE_DATE,
   RETIRE_EMPLOYEE_SUM_COUNT, RETIRE_EMPLOYEE_SUM_TIME, RETIRE_EMPLOYEE_EMAIL, RETIRE_EMPLOYEE_RETIRE_YN, EMPLOYEE_LAST_LOGIN_DATE
   ) 
   VALUES 
   (
   SEQ_EMP_RET_NO.NEXTVAL, '육라클', '202206', '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('22/01/06','RR/MM/DD'), 
   'M', '01006666666', TO_DATE('22/01/06','RR/MM/DD'), TO_DATE('22/06/06','RR/MM/DD'),
   5, 14, 'email6', 'Y', TO_DATE('22/06/06','RR/MM/DD')
   );


   INSERT 
     INTO TBL_RETIRE_EMPLOYEE 
     (
     RETIRE_EMPLOYEE_NO, EMPLOYEE_NAME, RETIRE_EMPLOYEE_ID, RETIRE_EMPLOYEE_PWD, RETIRE_EMPLOYEE_BIRTH, 
     RETIRE_EMPLOYEE_GENDER, RETIRE_EMPLOYEE_PHONE, RETIRE_EMPLOYEE_HIRE_DATE, RETIRE_EMPLOYEE_RETIRE_DATE,
     RETIRE_EMPLOYEE_SUM_COUNT, RETIRE_EMPLOYEE_SUM_TIME, RETIRE_EMPLOYEE_EMAIL, RETIRE_EMPLOYEE_RETIRE_YN, EMPLOYEE_LAST_LOGIN_DATE
     ) 
     VALUES 
     (
     SEQ_EMP_RET_NO.NEXTVAL, '칠라클', '202207', '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('22/01/07','RR/MM/DD'), 
     'M', '01007777777', TO_DATE('22/01/07','RR/MM/DD'), TO_DATE('22/06/07','RR/MM/DD'), 2, 55, 'email7', 'Y', TO_DATE('22/06/07','RR/MM/DD')
     );

INSERT 
  INTO TBL_RETIRE_EMPLOYEE 
  (
   RETIRE_EMPLOYEE_NO, EMPLOYEE_NAME, RETIRE_EMPLOYEE_ID, RETIRE_EMPLOYEE_PWD, RETIRE_EMPLOYEE_BIRTH, 
   RETIRE_EMPLOYEE_GENDER, RETIRE_EMPLOYEE_PHONE, RETIRE_EMPLOYEE_HIRE_DATE, RETIRE_EMPLOYEE_RETIRE_DATE,
   RETIRE_EMPLOYEE_SUM_COUNT, RETIRE_EMPLOYEE_SUM_TIME, RETIRE_EMPLOYEE_EMAIL, RETIRE_EMPLOYEE_RETIRE_YN, EMPLOYEE_LAST_LOGIN_DATE
   ) 
   VALUES 
   (
   SEQ_EMP_RET_NO.NEXTVAL, '팔라클', '202208', '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('22/01/08','RR/MM/DD'), 
   'M', '01008888888', TO_DATE('22/01/08','RR/MM/DD'), TO_DATE('22/06/08','RR/MM/DD'),
   1, 63, 'email8', 'Y', TO_DATE('22/06/08','RR/MM/DD')
   );

INSERT 
  INTO TBL_RETIRE_EMPLOYEE 
  (
   RETIRE_EMPLOYEE_NO, EMPLOYEE_NAME, RETIRE_EMPLOYEE_ID, RETIRE_EMPLOYEE_PWD, RETIRE_EMPLOYEE_BIRTH, 
   RETIRE_EMPLOYEE_GENDER, RETIRE_EMPLOYEE_PHONE, RETIRE_EMPLOYEE_HIRE_DATE, RETIRE_EMPLOYEE_RETIRE_DATE,
   RETIRE_EMPLOYEE_SUM_COUNT, RETIRE_EMPLOYEE_SUM_TIME, RETIRE_EMPLOYEE_EMAIL, RETIRE_EMPLOYEE_RETIRE_YN, EMPLOYEE_LAST_LOGIN_DATE
   ) 
   VALUES 
   (
   SEQ_EMP_RET_NO.NEXTVAL, '구라클', '202209', '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('22/01/09','RR/MM/DD'), 
   'F', '01009999999', TO_DATE('22/01/09','RR/MM/DD'), TO_DATE('22/06/09','RR/MM/DD'),
   3, 41, 'email9', 'Y', TO_DATE('22/06/09','RR/MM/DD')
   );

INSERT 
  INTO TBL_RETIRE_EMPLOYEE 
  (
  RETIRE_EMPLOYEE_NO, EMPLOYEE_NAME, RETIRE_EMPLOYEE_ID, RETIRE_EMPLOYEE_PWD,RETIRE_EMPLOYEE_BIRTH,
  RETIRE_EMPLOYEE_GENDER, RETIRE_EMPLOYEE_PHONE, RETIRE_EMPLOYEE_HIRE_DATE, RETIRE_EMPLOYEE_RETIRE_DATE, 
  RETIRE_EMPLOYEE_SUM_COUNT, RETIRE_EMPLOYEE_SUM_TIME, RETIRE_EMPLOYEE_EMAIL, RETIRE_EMPLOYEE_RETIRE_YN, EMPLOYEE_LAST_LOGIN_DATE
  )
  VALUES 
  (
  SEQ_EMP_RET_NO.NEXTVAL, '십라클', '202210', '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('22/01/10','RR/MM/DD'), 
  'M', '01010000000', TO_DATE('22/01/10','RR/MM/DD'), TO_DATE('22/06/10','RR/MM/DD'),
  0, 29, 'email10', 'Y', TO_DATE('22/06/10','RR/MM/DD')
  );
-- "TBL_RETIRE_ADMIN";

Insert 
  into TBL_RETIRE_ADMIN 
  (RETIRE_ADMIN_NO,
  RETIRE_ADMIN_NAME,
  RETIRE_ADMIN_ID,
  RETIRE_ADMIN_PWD,
  RETIRE_ADMIN_BIRTH,
  RETIRE_ADMIN_GENDER,
  RETIRE_ADMIN_PHONE,
  RETIRE_ADMIN_HIRE_DATE,
  RETIRE_ADMIN_RETIRE_DATE,
  RETIRE_ADMIN_RETIRE_YN,
  RETIRE_ADMIN_JOB,
  RETIRE_ADMIN_LAST_LOGIN_DATE,
  RETIRE_ADMIN_SALARY,RETIRE_ANNUAL_VACATION_USE) 
values 
( SEQ_TBL_RETIRE_ADMIN.NEXTVAL,'이은조','cleanup210608','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK'
 ,to_date('95/10/18','RR/MM/DD'),'F','01023890765',to_date('21/06/07','RR/MM/DD')
 ,to_date('22/07/02','RR/MM/DD'),'Y','보안담당자',to_date('22/07/01','RR/MM/DD'),3200000,7);

Insert 
  into TBL_RETIRE_ADMIN 
( RETIRE_ADMIN_NO,RETIRE_ADMIN_NAME,RETIRE_ADMIN_ID,RETIRE_ADMIN_PWD,RETIRE_ADMIN_BIRTH,RETIRE_ADMIN_GENDER
, RETIRE_ADMIN_PHONE,RETIRE_ADMIN_HIRE_DATE,RETIRE_ADMIN_RETIRE_DATE,RETIRE_ADMIN_RETIRE_YN,RETIRE_ADMIN_JOB
, RETIRE_ADMIN_LAST_LOGIN_DATE,RETIRE_ADMIN_SALARY,RETIRE_ANNUAL_VACATION_USE) 
values 
( SEQ_TBL_RETIRE_ADMIN.NEXTVAL,'이유미','cleanup200304','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK'
, to_date('92/08/06','RR/MM/DD'),'F','01011111111',to_date('20/03/04','RR/MM/DD'),to_date('22/07/03','RR/MM/DD'),'Y'
, '인사관리자',to_date('22/07/03','RR/MM/DD'),3400000,5);

Insert 
  into TBL_RETIRE_ADMIN 
( RETIRE_ADMIN_NO,RETIRE_ADMIN_NAME,RETIRE_ADMIN_ID,RETIRE_ADMIN_PWD,RETIRE_ADMIN_BIRTH,RETIRE_ADMIN_GENDER
, RETIRE_ADMIN_PHONE,RETIRE_ADMIN_HIRE_DATE,RETIRE_ADMIN_RETIRE_DATE,RETIRE_ADMIN_RETIRE_YN,RETIRE_ADMIN_JOB
, RETIRE_ADMIN_LAST_LOGIN_DATE,RETIRE_ADMIN_SALARY,RETIRE_ANNUAL_VACATION_USE) 
values 
(SEQ_TBL_RETIRE_ADMIN.NEXTVAL,'조은솔','cleanup200305','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK'
,to_date('92/08/06','RR/MM/DD'),'F','01022222222',to_date('20/03/05','RR/MM/DD'),to_date('22/07/03','RR/MM/DD')
,'Y','일반관리자',to_date('22/07/03','RR/MM/DD'),3400000,2);

Insert 
  into TBL_RETIRE_ADMIN (RETIRE_ADMIN_NO,RETIRE_ADMIN_NAME,RETIRE_ADMIN_ID,RETIRE_ADMIN_PWD
  ,RETIRE_ADMIN_BIRTH,RETIRE_ADMIN_GENDER,RETIRE_ADMIN_PHONE,RETIRE_ADMIN_HIRE_DATE,RETIRE_ADMIN_RETIRE_DATE
  ,RETIRE_ADMIN_RETIRE_YN,RETIRE_ADMIN_JOB,RETIRE_ADMIN_LAST_LOGIN_DATE,RETIRE_ADMIN_SALARY,RETIRE_ANNUAL_VACATION_USE) 
values 
 (SEQ_TBL_RETIRE_ADMIN.NEXTVAL,'구웅','cleanup210609','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK',
  to_date('92/08/06','RR/MM/DD'),'M','01033333333',to_date('21/06/08','RR/MM/DD'),to_date('22/07/02','RR/MM/DD'),'Y',
  '보안담당자',to_date('22/07/01','RR/MM/DD'),3200000,7);
  
Insert into TBL_RETIRE_ADMIN (RETIRE_ADMIN_NO,RETIRE_ADMIN_NAME,RETIRE_ADMIN_ID,RETIRE_ADMIN_PWD,RETIRE_ADMIN_BIRTH,RETIRE_ADMIN_GENDER,
RETIRE_ADMIN_PHONE,RETIRE_ADMIN_HIRE_DATE,RETIRE_ADMIN_RETIRE_DATE,RETIRE_ADMIN_RETIRE_YN,RETIRE_ADMIN_JOB,RETIRE_ADMIN_LAST_LOGIN_DATE,
RETIRE_ADMIN_SALARY,RETIRE_ANNUAL_VACATION_USE) 
values 
(SEQ_TBL_RETIRE_ADMIN.NEXTVAL,'조이','cleanup200309','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK'
,to_date('92/08/06','RR/MM/DD'),'F','01044444444',to_date('20/03/04','RR/MM/DD'),to_date('22/07/03','RR/MM/DD'),
'Y','인사관리자',to_date('22/07/03','RR/MM/DD'),3400000,5);

-- "TBL_ADMIN_PAY"; 
INSERT INTO TBL_ADMIN_PAY
( 
  PAY_HISTORY_ADMIN_NO, PAY_ADMIN_NO, PAY_ADMIN_DATE
)
VALUES
(
  SEQ_TBL_ADMIN_PAY.NEXTVAL, 1, TO_DATE('22-06-01', 'YY-MM-DD')
);

INSERT INTO TBL_ADMIN_PAY
( 
  PAY_HISTORY_ADMIN_NO, PAY_ADMIN_NO, PAY_ADMIN_DATE
)
VALUES
(
  SEQ_TBL_ADMIN_PAY.NEXTVAL, 2, TO_DATE('22-06-01', 'YY-MM-DD')
);

INSERT INTO TBL_ADMIN_PAY
( 
  PAY_HISTORY_ADMIN_NO, PAY_ADMIN_NO, PAY_ADMIN_DATE
)
VALUES
(
  SEQ_TBL_ADMIN_PAY.NEXTVAL, 3, TO_DATE('22-06-01', 'YY-MM-DD')
);

INSERT INTO TBL_ADMIN_PAY
( 
  PAY_HISTORY_ADMIN_NO, PAY_ADMIN_NO, PAY_ADMIN_DATE
)
VALUES
(
  SEQ_TBL_ADMIN_PAY.NEXTVAL, 4, TO_DATE('22-06-01', 'YY-MM-DD')
);

INSERT INTO TBL_ADMIN_PAY
( 
  PAY_HISTORY_ADMIN_NO, PAY_ADMIN_NO, PAY_ADMIN_DATE
)
VALUES
(
  SEQ_TBL_ADMIN_PAY.NEXTVAL, 5, TO_DATE('22-06-01', 'YY-MM-DD')
);

INSERT INTO TBL_ADMIN_PAY
( 
  PAY_HISTORY_ADMIN_NO, PAY_ADMIN_NO, PAY_ADMIN_DATE
)
VALUES
(
  SEQ_TBL_ADMIN_PAY.NEXTVAL, 6, TO_DATE('22-06-01', 'YY-MM-DD')
);

INSERT INTO TBL_ADMIN_PAY
( 
  PAY_HISTORY_ADMIN_NO, PAY_ADMIN_NO, PAY_ADMIN_DATE
)
VALUES
(
  SEQ_TBL_ADMIN_PAY.NEXTVAL, 7, TO_DATE('22-06-01', 'YY-MM-DD')
);

INSERT INTO TBL_ADMIN_PAY
( 
  PAY_HISTORY_ADMIN_NO, PAY_ADMIN_NO, PAY_ADMIN_DATE
)
VALUES
(
  SEQ_TBL_ADMIN_PAY.NEXTVAL, 1, TO_DATE('22-07-01', 'YY-MM-DD')
);

INSERT INTO TBL_ADMIN_PAY
( 
  PAY_HISTORY_ADMIN_NO, PAY_ADMIN_NO, PAY_ADMIN_DATE
)
VALUES
(
  SEQ_TBL_ADMIN_PAY.NEXTVAL, 2, TO_DATE('22-07-01', 'YY-MM-DD')
);

INSERT INTO TBL_ADMIN_PAY
( 
  PAY_HISTORY_ADMIN_NO, PAY_ADMIN_NO, PAY_ADMIN_DATE
)
VALUES
(
  SEQ_TBL_ADMIN_PAY.NEXTVAL, 3, TO_DATE('22-07-01', 'YY-MM-DD')
);

INSERT INTO TBL_ADMIN_PAY
( 
  PAY_HISTORY_ADMIN_NO, PAY_ADMIN_NO, PAY_ADMIN_DATE
)
VALUES
(
  SEQ_TBL_ADMIN_PAY.NEXTVAL, 4, TO_DATE('22-07-01', 'YY-MM-DD')
);

INSERT INTO TBL_ADMIN_PAY
( 
  PAY_HISTORY_ADMIN_NO, PAY_ADMIN_NO, PAY_ADMIN_DATE
)
VALUES
(
  SEQ_TBL_ADMIN_PAY.NEXTVAL, 5, TO_DATE('22-07-01', 'YY-MM-DD')
);

INSERT INTO TBL_ADMIN_PAY
( 
  PAY_HISTORY_ADMIN_NO, PAY_ADMIN_NO, PAY_ADMIN_DATE
)
VALUES
(
  SEQ_TBL_ADMIN_PAY.NEXTVAL, 6, TO_DATE('22-07-01', 'YY-MM-DD')
);

INSERT INTO TBL_ADMIN_PAY
( 
  PAY_HISTORY_ADMIN_NO, PAY_ADMIN_NO, PAY_ADMIN_DATE
)
VALUES
(
  SEQ_TBL_ADMIN_PAY.NEXTVAL, 7, TO_DATE('22-07-01', 'YY-MM-DD')
);






-- "TBL_APPLY_EMPLOYEE"; 

INSERT INTO TBL_APPLY_EMPLOYEE
(
  APPLY_EMPLOYEE_NO, APPLY_RESERVATION_NO, APPLY_CANCEL_YN, CHECK_EMPLOYEE_YN
)
VALUES
(
  1, 1, 'N', 'Y'
);

INSERT INTO TBL_APPLY_EMPLOYEE
(
  APPLY_EMPLOYEE_NO, APPLY_RESERVATION_NO, APPLY_CANCEL_YN, CHECK_EMPLOYEE_YN
)
VALUES
(
  2, 2, 'N', 'Y'
);

INSERT INTO TBL_APPLY_EMPLOYEE
(
  APPLY_EMPLOYEE_NO, APPLY_RESERVATION_NO, APPLY_CANCEL_YN, CHECK_EMPLOYEE_YN
)
VALUES
(
  3, 3, 'N', 'Y'
);
INSERT INTO TBL_APPLY_EMPLOYEE
(
  APPLY_EMPLOYEE_NO, APPLY_RESERVATION_NO, APPLY_CANCEL_YN, CHECK_EMPLOYEE_YN
)
VALUES
(
  4, 3, 'N', 'Y'
);
INSERT INTO TBL_APPLY_EMPLOYEE
(
  APPLY_EMPLOYEE_NO, APPLY_RESERVATION_NO, APPLY_CANCEL_YN, CHECK_EMPLOYEE_YN
)
VALUES
(
  5, 4, 'N', 'Y'
);
INSERT INTO TBL_APPLY_EMPLOYEE
(
  APPLY_EMPLOYEE_NO, APPLY_RESERVATION_NO, APPLY_CANCEL_YN, CHECK_EMPLOYEE_YN
)
VALUES
(
  6, 5, 'N', 'Y'
);
INSERT INTO TBL_APPLY_EMPLOYEE
(
  APPLY_EMPLOYEE_NO, APPLY_RESERVATION_NO, APPLY_CANCEL_YN, CHECK_EMPLOYEE_YN
)
VALUES
(
  7, 6, 'N', 'Y'
);

INSERT INTO TBL_APPLY_EMPLOYEE
(
  APPLY_EMPLOYEE_NO, APPLY_RESERVATION_NO, APPLY_CANCEL_YN, CHECK_EMPLOYEE_YN
)
VALUES
(
  1, 7, 'N', 'N'
);

INSERT INTO TBL_APPLY_EMPLOYEE
(
  APPLY_EMPLOYEE_NO, APPLY_RESERVATION_NO, APPLY_CANCEL_YN, CHECK_EMPLOYEE_YN
)
VALUES
(
  2, 8, 'N', 'N'
);

INSERT INTO TBL_APPLY_EMPLOYEE
(
  APPLY_EMPLOYEE_NO, APPLY_RESERVATION_NO, APPLY_CANCEL_YN, CHECK_EMPLOYEE_YN
)
VALUES
(
  3, 8, 'N', 'N'
);
INSERT INTO TBL_APPLY_EMPLOYEE
(
  APPLY_EMPLOYEE_NO, APPLY_RESERVATION_NO, APPLY_CANCEL_YN, CHECK_EMPLOYEE_YN
)
VALUES
(
  4, 9, 'N', 'N'
);
INSERT INTO TBL_APPLY_EMPLOYEE
(
  APPLY_EMPLOYEE_NO, APPLY_RESERVATION_NO, APPLY_CANCEL_YN, CHECK_EMPLOYEE_YN
)
VALUES
(
  5, 10, 'N', 'N'
);
INSERT INTO TBL_APPLY_EMPLOYEE
(
  APPLY_EMPLOYEE_NO, APPLY_RESERVATION_NO, APPLY_CANCEL_YN, CHECK_EMPLOYEE_YN
)
VALUES
(
  6, 11, 'N', 'N'
);
INSERT INTO TBL_APPLY_EMPLOYEE
(
  APPLY_EMPLOYEE_NO, APPLY_RESERVATION_NO, APPLY_CANCEL_YN, CHECK_EMPLOYEE_YN
)
VALUES
(
  7, 12, 'N', 'N'
);

-- "TBL_CHECKLIST";x
-- "TBL_EMPLOYEE_PICTURE";x
-- "TBL_ADMIN_PICTURE";x
-- "TBL_BOOKMARK"; 

INSERT INTO TBL_BOOKMARK
(
  BOOKMARK_NO, BOOKMARK_CANCEL_YN, BOOKMARK_EMPLOYEE_NO, BOOKMARK_RESERVATION_NO
)
VALUES
(
  SEQ_TBL_BOOKMARK.NEXTVAL, 'N', 1, 1
);

INSERT INTO TBL_BOOKMARK
(
  BOOKMARK_NO, BOOKMARK_CANCEL_YN, BOOKMARK_EMPLOYEE_NO, BOOKMARK_RESERVATION_NO
)
VALUES
(
  SEQ_TBL_BOOKMARK.NEXTVAL, 'N', 1, 2
);

INSERT INTO TBL_BOOKMARK
(
  BOOKMARK_NO, BOOKMARK_CANCEL_YN, BOOKMARK_EMPLOYEE_NO, BOOKMARK_RESERVATION_NO
)
VALUES
(
  SEQ_TBL_BOOKMARK.NEXTVAL, 'N', 1, 3
);
INSERT INTO TBL_BOOKMARK
(
  BOOKMARK_NO, BOOKMARK_CANCEL_YN, BOOKMARK_EMPLOYEE_NO, BOOKMARK_RESERVATION_NO
)
VALUES
(
  SEQ_TBL_BOOKMARK.NEXTVAL, 'N', 2, 1
);
INSERT INTO TBL_BOOKMARK
(
  BOOKMARK_NO, BOOKMARK_CANCEL_YN, BOOKMARK_EMPLOYEE_NO, BOOKMARK_RESERVATION_NO
)
VALUES
(
  SEQ_TBL_BOOKMARK.NEXTVAL, 'N', 2, 2
);
INSERT INTO TBL_BOOKMARK
(
  BOOKMARK_NO, BOOKMARK_CANCEL_YN, BOOKMARK_EMPLOYEE_NO, BOOKMARK_RESERVATION_NO
)
VALUES
(
  SEQ_TBL_BOOKMARK.NEXTVAL, 'N', 3, 1
);
INSERT INTO TBL_BOOKMARK
(
  BOOKMARK_NO, BOOKMARK_CANCEL_YN, BOOKMARK_EMPLOYEE_NO, BOOKMARK_RESERVATION_NO
)
VALUES
(
  SEQ_TBL_BOOKMARK.NEXTVAL, 'N', 3, 3
);
INSERT INTO TBL_BOOKMARK
(
  BOOKMARK_NO, BOOKMARK_CANCEL_YN, BOOKMARK_EMPLOYEE_NO, BOOKMARK_RESERVATION_NO
)
VALUES
(
  SEQ_TBL_BOOKMARK.NEXTVAL, 'N', 1, 7
);

INSERT INTO TBL_BOOKMARK
(
  BOOKMARK_NO, BOOKMARK_CANCEL_YN, BOOKMARK_EMPLOYEE_NO, BOOKMARK_RESERVATION_NO
)
VALUES
(
  SEQ_TBL_BOOKMARK.NEXTVAL, 'N', 1, 8
);

INSERT INTO TBL_BOOKMARK
(
  BOOKMARK_NO, BOOKMARK_CANCEL_YN, BOOKMARK_EMPLOYEE_NO, BOOKMARK_RESERVATION_NO
)
VALUES
(
  SEQ_TBL_BOOKMARK.NEXTVAL, 'N', 1, 9
);
INSERT INTO TBL_BOOKMARK
(
  BOOKMARK_NO, BOOKMARK_CANCEL_YN, BOOKMARK_EMPLOYEE_NO, BOOKMARK_RESERVATION_NO
)
VALUES
(
  SEQ_TBL_BOOKMARK.NEXTVAL, 'N', 2, 7
);
INSERT INTO TBL_BOOKMARK
(
  BOOKMARK_NO, BOOKMARK_CANCEL_YN, BOOKMARK_EMPLOYEE_NO, BOOKMARK_RESERVATION_NO
)
VALUES
(
  SEQ_TBL_BOOKMARK.NEXTVAL, 'N', 2, 8
);
INSERT INTO TBL_BOOKMARK
(
  BOOKMARK_NO, BOOKMARK_CANCEL_YN, BOOKMARK_EMPLOYEE_NO, BOOKMARK_RESERVATION_NO
)
VALUES
(
  SEQ_TBL_BOOKMARK.NEXTVAL, 'N', 3, 9
);
INSERT INTO TBL_BOOKMARK
(
  BOOKMARK_NO, BOOKMARK_CANCEL_YN, BOOKMARK_EMPLOYEE_NO, BOOKMARK_RESERVATION_NO
)
VALUES
(
  SEQ_TBL_BOOKMARK.NEXTVAL, 'N', 3, 10
);

-- "TBL_SURCHARGE"; 

INSERT INTO TBL_SURCHARGE
(
  SURCHARGE_INSURANCE, SURCHARGE_COMMISSION, SURCHARGE_BONUS
)
VALUES
(
  8, 5, 200000
);

-- "TBL_VACATION";

Insert into TBL_VACATION (VACATION_NO,REQUEST_DATE,REQUEST_ADMIN,DRAFTER,VACATION_NAME,VACATION_FIRST_CONFIRM_YN,VACATION_SECOND_CONFIRM_YN,VACATION_LAST_CONFIRM_YN,VACATION_START_DATE,VACATION_END_DATE,VACATION_REASON,VACATION_RETURN_YN,ADMIN_NO) values (SEQ_TBL_VACATION.NEXTVAL,to_date('22/07/01','RR/MM/DD'),'이시원','이시원','연차','Y','Y','Y',to_date('22/07/28','RR/MM/DD'),to_date('22/07/29','RR/MM/DD'),'연차 사용','N',1);
Insert into TBL_VACATION (VACATION_NO,REQUEST_DATE,REQUEST_ADMIN,DRAFTER,VACATION_NAME,VACATION_FIRST_CONFIRM_YN,VACATION_SECOND_CONFIRM_YN,VACATION_LAST_CONFIRM_YN,VACATION_START_DATE,VACATION_END_DATE,VACATION_REASON,VACATION_RETURN_YN,ADMIN_NO) values (SEQ_TBL_VACATION.NEXTVAL,to_date('22/07/01','RR/MM/DD'),'서보라','이시원','기타','Y','N','N',to_date('22/07/28','RR/MM/DD'),to_date('22/07/29','RR/MM/DD'),'이유가 있습니다..','N',2);
Insert into TBL_VACATION (VACATION_NO,REQUEST_DATE,REQUEST_ADMIN,DRAFTER,VACATION_NAME,VACATION_FIRST_CONFIRM_YN,VACATION_SECOND_CONFIRM_YN,VACATION_LAST_CONFIRM_YN,VACATION_START_DATE,VACATION_END_DATE,VACATION_REASON,VACATION_RETURN_YN,ADMIN_NO) values (SEQ_TBL_VACATION.NEXTVAL,to_date('22/07/07','RR/MM/DD'),'신순록','이시원','경조사','Y','Y','Y',to_date('22/07/27','RR/MM/DD'),to_date('22/07/27','RR/MM/DD'),'결혼식','N',3);
Insert into TBL_VACATION (VACATION_NO,REQUEST_DATE,REQUEST_ADMIN,DRAFTER,VACATION_NAME,VACATION_FIRST_CONFIRM_YN,VACATION_SECOND_CONFIRM_YN,VACATION_LAST_CONFIRM_YN,VACATION_START_DATE,VACATION_END_DATE,VACATION_REASON,VACATION_RETURN_YN,ADMIN_NO) values (SEQ_TBL_VACATION.NEXTVAL,to_date('22/07/12','RR/MM/DD'),'조완','이시원','공가','Y','N','N',to_date('22/07/29','RR/MM/DD'),to_date('22/07/29','RR/MM/DD'),'예비군','N',4);
Insert into TBL_VACATION (VACATION_NO,REQUEST_DATE,REQUEST_ADMIN,DRAFTER,VACATION_NAME,VACATION_FIRST_CONFIRM_YN,VACATION_SECOND_CONFIRM_YN,VACATION_LAST_CONFIRM_YN,VACATION_START_DATE,VACATION_END_DATE,VACATION_REASON,VACATION_RETURN_YN,ADMIN_NO) values (SEQ_TBL_VACATION.NEXTVAL,to_date('22/07/22','RR/MM/DD'),'조쉬','이시원','기타','N','N','N',to_date('22/07/12','RR/MM/DD'),to_date('22/07/14','RR/MM/DD'),'쉬고싶어요','Y',5);
Insert into TBL_VACATION (VACATION_NO,REQUEST_DATE,REQUEST_ADMIN,DRAFTER,VACATION_NAME,VACATION_FIRST_CONFIRM_YN,VACATION_SECOND_CONFIRM_YN,VACATION_LAST_CONFIRM_YN,VACATION_START_DATE,VACATION_END_DATE,VACATION_REASON,VACATION_RETURN_YN,ADMIN_NO) values (SEQ_TBL_VACATION.NEXTVAL,to_date('22/07/22','RR/MM/DD'),'조광조','이시원','연차','Y','N','N',to_date('22/07/14','RR/MM/DD'),to_date('22/07/15','RR/MM/DD'),'연차','Y',7);
Insert into TBL_VACATION (VACATION_NO,REQUEST_DATE,REQUEST_ADMIN,DRAFTER,VACATION_NAME,VACATION_FIRST_CONFIRM_YN,VACATION_SECOND_CONFIRM_YN,VACATION_LAST_CONFIRM_YN,VACATION_START_DATE,VACATION_END_DATE,VACATION_REASON,VACATION_RETURN_YN,ADMIN_NO) values (SEQ_TBL_VACATION.NEXTVAL,to_date('22/07/01','RR/MM/DD'),'이시원','이시원','연차','Y','Y','Y',to_date('22/07/28','RR/MM/DD'),to_date('22/07/29','RR/MM/DD'),'연차 사용','N',1);
Insert into TBL_VACATION (VACATION_NO,REQUEST_DATE,REQUEST_ADMIN,DRAFTER,VACATION_NAME,VACATION_FIRST_CONFIRM_YN,VACATION_SECOND_CONFIRM_YN,VACATION_LAST_CONFIRM_YN,VACATION_START_DATE,VACATION_END_DATE,VACATION_REASON,VACATION_RETURN_YN,ADMIN_NO) values (SEQ_TBL_VACATION.NEXTVAL,to_date('22/07/01','RR/MM/DD'),'서보라','이시원','기타','Y','N','N',to_date('22/07/28','RR/MM/DD'),to_date('22/07/29','RR/MM/DD'),'이유가 있습니다..','N',2);
Insert into TBL_VACATION (VACATION_NO,REQUEST_DATE,REQUEST_ADMIN,DRAFTER,VACATION_NAME,VACATION_FIRST_CONFIRM_YN,VACATION_SECOND_CONFIRM_YN,VACATION_LAST_CONFIRM_YN,VACATION_START_DATE,VACATION_END_DATE,VACATION_REASON,VACATION_RETURN_YN,ADMIN_NO) values (SEQ_TBL_VACATION.NEXTVAL,to_date('22/07/07','RR/MM/DD'),'신순록','이시원','경조사','Y','Y','Y',to_date('22/07/27','RR/MM/DD'),to_date('22/07/27','RR/MM/DD'),'결혼식','N',3);
Insert into TBL_VACATION (VACATION_NO,REQUEST_DATE,REQUEST_ADMIN,DRAFTER,VACATION_NAME,VACATION_FIRST_CONFIRM_YN,VACATION_SECOND_CONFIRM_YN,VACATION_LAST_CONFIRM_YN,VACATION_START_DATE,VACATION_END_DATE,VACATION_REASON,VACATION_RETURN_YN,ADMIN_NO) values (SEQ_TBL_VACATION.NEXTVAL,to_date('22/07/12','RR/MM/DD'),'조완','이시원','공가','Y','N','N',to_date('22/07/29','RR/MM/DD'),to_date('22/07/29','RR/MM/DD'),'예비군','N',4);
Insert into TBL_VACATION (VACATION_NO,REQUEST_DATE,REQUEST_ADMIN,DRAFTER,VACATION_NAME,VACATION_FIRST_CONFIRM_YN,VACATION_SECOND_CONFIRM_YN,VACATION_LAST_CONFIRM_YN,VACATION_START_DATE,VACATION_END_DATE,VACATION_REASON,VACATION_RETURN_YN,ADMIN_NO) values (SEQ_TBL_VACATION.NEXTVAL,to_date('22/07/22','RR/MM/DD'),'조쉬','이시원','기타','N','N','N',to_date('22/07/12','RR/MM/DD'),to_date('22/07/14','RR/MM/DD'),'쉬고싶어요','Y',5);
Insert into TBL_VACATION (VACATION_NO,REQUEST_DATE,REQUEST_ADMIN,DRAFTER,VACATION_NAME,VACATION_FIRST_CONFIRM_YN,VACATION_SECOND_CONFIRM_YN,VACATION_LAST_CONFIRM_YN,VACATION_START_DATE,VACATION_END_DATE,VACATION_REASON,VACATION_RETURN_YN,ADMIN_NO) values (SEQ_TBL_VACATION.NEXTVAL,to_date('22/07/22','RR/MM/DD'),'조광조','이시원','연차','Y','N','N',to_date('22/07/14','RR/MM/DD'),to_date('22/07/15','RR/MM/DD'),'연차','Y',7);

-- "TBL_EMPLOYEE_PAY"; 

INSERT INTO TBL_EMPLOYEE_PAY
( 
  PAY_HISTORY_EMPLOYEE_NO, PAY_EMPLOYEE_DATE, PAY_APPLY_RESERVATION_NO, PAY_APPLY_EMPLOYEE_NO
)
VALUES
(
  SEQ_TBL_EMPLOYEE_PAY.NEXTVAL, TO_DATE('22-07-28', 'YY-MM-DD'), 1, 1
);

INSERT INTO TBL_EMPLOYEE_PAY
( 
  PAY_HISTORY_EMPLOYEE_NO, PAY_EMPLOYEE_DATE, PAY_APPLY_RESERVATION_NO, PAY_APPLY_EMPLOYEE_NO
)
VALUES
(
  SEQ_TBL_EMPLOYEE_PAY.NEXTVAL, TO_DATE('22-07-28', 'YY-MM-DD'), 2, 2
);

INSERT INTO TBL_EMPLOYEE_PAY
( 
  PAY_HISTORY_EMPLOYEE_NO, PAY_EMPLOYEE_DATE, PAY_APPLY_RESERVATION_NO, PAY_APPLY_EMPLOYEE_NO
)
VALUES
(
  SEQ_TBL_EMPLOYEE_PAY.NEXTVAL, TO_DATE('22-07-28', 'YY-MM-DD'), 3, 3
);

INSERT INTO TBL_EMPLOYEE_PAY
( 
  PAY_HISTORY_EMPLOYEE_NO, PAY_EMPLOYEE_DATE, PAY_APPLY_RESERVATION_NO, PAY_APPLY_EMPLOYEE_NO
)
VALUES
(
  SEQ_TBL_EMPLOYEE_PAY.NEXTVAL, TO_DATE('22-07-28', 'YY-MM-DD'), 3, 4
);

INSERT INTO TBL_EMPLOYEE_PAY
( 
  PAY_HISTORY_EMPLOYEE_NO, PAY_EMPLOYEE_DATE, PAY_APPLY_RESERVATION_NO, PAY_APPLY_EMPLOYEE_NO
)
VALUES
(
  SEQ_TBL_EMPLOYEE_PAY.NEXTVAL, TO_DATE('22-07-28', 'YY-MM-DD'), 4, 5
);

INSERT INTO TBL_EMPLOYEE_PAY
( 
  PAY_HISTORY_EMPLOYEE_NO, PAY_EMPLOYEE_DATE, PAY_APPLY_RESERVATION_NO, PAY_APPLY_EMPLOYEE_NO
)
VALUES
(
  SEQ_TBL_EMPLOYEE_PAY.NEXTVAL, TO_DATE('22-07-28', 'YY-MM-DD'), 5, 6
);

INSERT INTO TBL_EMPLOYEE_PAY
( 
  PAY_HISTORY_EMPLOYEE_NO, PAY_EMPLOYEE_DATE, PAY_APPLY_RESERVATION_NO, PAY_APPLY_EMPLOYEE_NO
)
VALUES
(
  SEQ_TBL_EMPLOYEE_PAY.NEXTVAL, TO_DATE('22-07-31', 'YY-MM-DD'), 6, 7
);



-- "TBL_NOTIFICATION"; 

INSERT INTO TBL_NOTIFICATION
(
  NOTIFICATION_NO, NOTIFIVATION_TEXT, NOTIFIVATION_CREATE_TIME, NOTIFIVATION_READ_YN, NOTIFIVATION_ADMIN_YN
, NOTIFIVATION_EMPLOYEE_NO, NOTIFIVATION_RESERVATION_NO, NOTIFIVATION_ADMIN_NO
)
VALUES
(
  SEQ_TBL_NOTIFICATION.NEXTVAL, '즐겨찾기 하신 예약건이 지원 가능 상태로 변경되었습니다.', TO_DATE('2022-07-27 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'N', 'N'
, 1, 10, 4
);
INSERT INTO TBL_NOTIFICATION
(
  NOTIFICATION_NO, NOTIFIVATION_TEXT, NOTIFIVATION_CREATE_TIME, NOTIFIVATION_READ_YN, NOTIFIVATION_ADMIN_YN
, NOTIFIVATION_EMPLOYEE_NO, NOTIFIVATION_RESERVATION_NO, NOTIFIVATION_ADMIN_NO
)
VALUES
(
  SEQ_TBL_NOTIFICATION.NEXTVAL, '즐겨찾기 하신 예약건이 지원 가능 상태로 변경되었습니다.', TO_DATE('2022-07-27 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'N', 'N'
, 2, 10, 4
);
INSERT INTO TBL_NOTIFICATION
(
  NOTIFICATION_NO, NOTIFIVATION_TEXT, NOTIFIVATION_CREATE_TIME, NOTIFIVATION_READ_YN, NOTIFIVATION_ADMIN_YN
, NOTIFIVATION_EMPLOYEE_NO, NOTIFIVATION_RESERVATION_NO, NOTIFIVATION_ADMIN_NO
)
VALUES
(
  SEQ_TBL_NOTIFICATION.NEXTVAL, '즐겨찾기 하신 예약건이 지원 가능 상태로 변경되었습니다.', TO_DATE('2022-07-27 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'N', 'N'
, 3, 10, 4
);
INSERT INTO TBL_NOTIFICATION
(
  NOTIFICATION_NO, NOTIFIVATION_TEXT, NOTIFIVATION_CREATE_TIME, NOTIFIVATION_READ_YN, NOTIFIVATION_ADMIN_YN
, NOTIFIVATION_EMPLOYEE_NO, NOTIFIVATION_RESERVATION_NO, NOTIFIVATION_ADMIN_NO
)
VALUES
(
  SEQ_TBL_NOTIFICATION.NEXTVAL, '즐겨찾기 하신 예약건이 지원 가능 상태로 변경되었습니다.', TO_DATE('2022-07-27 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'N', 'N'
, 1, 11, 4
);

INSERT INTO TBL_NOTIFICATION
(
  NOTIFICATION_NO, NOTIFIVATION_TEXT, NOTIFIVATION_CREATE_TIME, NOTIFIVATION_READ_YN, NOTIFIVATION_ADMIN_YN
, NOTIFIVATION_EMPLOYEE_NO, NOTIFIVATION_RESERVATION_NO, NOTIFIVATION_ADMIN_NO
)
VALUES
(
  SEQ_TBL_NOTIFICATION.NEXTVAL, '지원하셨던 예약건에서 관리자가 직원님의 상태를 지원취소 상태로 변경했습니다.', TO_DATE('2022-07-27 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'N', 'N'
, 1, 4, 4
);

INSERT INTO TBL_NOTIFICATION
(
  NOTIFICATION_NO, NOTIFIVATION_TEXT, NOTIFIVATION_CREATE_TIME, NOTIFIVATION_READ_YN, NOTIFIVATION_ADMIN_YN
, NOTIFIVATION_EMPLOYEE_NO, NOTIFIVATION_RESERVATION_NO, NOTIFIVATION_ADMIN_NO
)
VALUES
(
  SEQ_TBL_NOTIFICATION.NEXTVAL, '해당 예약건에 직원추가가 필요합니다.', TO_DATE('2022-07-27 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'N', 'Y'
, NULL , 4, 4
);

INSERT INTO TBL_NOTIFICATION
(
  NOTIFICATION_NO, NOTIFIVATION_TEXT, NOTIFIVATION_CREATE_TIME, NOTIFIVATION_READ_YN, NOTIFIVATION_ADMIN_YN
, NOTIFIVATION_EMPLOYEE_NO, NOTIFIVATION_RESERVATION_NO, NOTIFIVATION_ADMIN_NO
)
VALUES
(
  SEQ_TBL_NOTIFICATION.NEXTVAL, '해당 예약건에 직원추가가 필요합니다.', TO_DATE('2022-07-27 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'N', 'Y'
, NULL , 6, 4
);

-- "TBL_ADMIN_IP_ADRESS";x
-- "EMPLOYEE_REST_COMMIT";

Insert into C##PROJECT_CLEAN.TBL_REASON (ADMIN_NO,EMPLOYEE_NO,REASON,REGIST_REASON_DATE) values (1,1,null,to_date('22/01/01','RR/MM/DD'));
Insert into C##PROJECT_CLEAN.TBL_REASON (ADMIN_NO,EMPLOYEE_NO,REASON,REGIST_REASON_DATE) values (7,1,null,to_date('22/01/01','RR/MM/DD'));
Insert into C##PROJECT_CLEAN.TBL_REASON (ADMIN_NO,EMPLOYEE_NO,REASON,REGIST_REASON_DATE) values (1,2,null,to_date('22/01/01','RR/MM/DD'));
Insert into C##PROJECT_CLEAN.TBL_REASON (ADMIN_NO,EMPLOYEE_NO,REASON,REGIST_REASON_DATE) values (7,2,null,to_date('22/01/01','RR/MM/DD'));
Insert into C##PROJECT_CLEAN.TBL_REASON (ADMIN_NO,EMPLOYEE_NO,REASON,REGIST_REASON_DATE) values (1,3,null,to_date('22/01/01','RR/MM/DD'));
Insert into C##PROJECT_CLEAN.TBL_REASON (ADMIN_NO,EMPLOYEE_NO,REASON,REGIST_REASON_DATE) values (7,3,null,to_date('22/01/01','RR/MM/DD'));
Insert into C##PROJECT_CLEAN.TBL_REASON (ADMIN_NO,EMPLOYEE_NO,REASON,REGIST_REASON_DATE) values (1,4,null,to_date('22/01/01','RR/MM/DD'));
Insert into C##PROJECT_CLEAN.TBL_REASON (ADMIN_NO,EMPLOYEE_NO,REASON,REGIST_REASON_DATE) values (7,4,null,to_date('22/01/01','RR/MM/DD'));
Insert into C##PROJECT_CLEAN.TBL_REASON (ADMIN_NO,EMPLOYEE_NO,REASON,REGIST_REASON_DATE) values (1,5,null,to_date('22/01/01','RR/MM/DD'));
Insert into C##PROJECT_CLEAN.TBL_REASON (ADMIN_NO,EMPLOYEE_NO,REASON,REGIST_REASON_DATE) values (7,5,null,to_date('22/01/01','RR/MM/DD'));
COMMIT;