CREATE USER C##PROJECT_CLEAN IDENTIFIED BY PROJECT_CLEAN;                           
GRANT CONNECT, RESOURCE, CREATE VIEW TO C##PROJECT_CLEAN;

ALTER USER C##PROJECT_CLEAN DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
ALTER USER C##PROJECT_CLEAN QUOTA 1024M ON SYSTEM;