-- "TBL_AUTHORITY"

INSERT
  INTO TBL_AUTHORITY
  (
  AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC
  )
  VALUES
  (
  1, 'ROLE_CLIENT', '고객'
  );



INSERT
  INTO TBL_AUTHORITY
  (
  AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC
  )
  VALUES
  (
  2, 'ROLE_MEMBER', '모든 사용자'
  );

INSERT
  INTO TBL_AUTHORITY
  (
  AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC
  )
  VALUES
  (
  3, 'ROLE_EMPLOYEE', '직원'
  );
  
INSERT
  INTO TBL_AUTHORITY
  (
  AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC
  )
  VALUES
  (
  4, 'ROLE_ADMIN', '모든 관리자'
  );  

INSERT
  INTO TBL_AUTHORITY
  (
  AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC
  )
  VALUES
  (
  5, 'ROLE_ADMIN_BOSS', '사장'
  );  


INSERT
  INTO TBL_AUTHORITY
  (
  AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC
  )
  VALUES
  (
  6, 'ROLE_ADMIN_SEC', '보안 담당자'
  );
  
INSERT
  INTO TBL_AUTHORITY
  (
  AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC
  )
  VALUES
  (
  7, 'ROLE_ADMIN_HR', '인사 담당자'
  );  

INSERT
  INTO TBL_AUTHORITY
  (
  AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC
  )
  VALUES
  (
  8, 'ROLE_ADMIN_FNC', '재정 담당자'
  );

INSERT
  INTO TBL_AUTHORITY
  (
  AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC
  )
  VALUES
  (
  9, 'ROLE_FAIL', '로그인 실패'
  );

-- "TBL_ADMIN";

INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL,'이시원','cleanup'||TO_CHAR(SYSDATE, 'YYMMDD')
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('98/02/18','RR/MM/DD'),'F'
, '010-1111-1111', TO_DATE('22/07/05','RR/MM/DD'), NULL
, 'N','총관리자', TO_DATE('22/07/05','RR/MM/DD')
, 20000000, 3, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);
INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL, '서보라', 'cleanup210823'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('94/04/27','RR/MM/DD'), 'F'
, '010-2222-2222', TO_DATE('21/08/23','RR/MM/DD'), NULL
, 'N', '인사관리자', TO_DATE('22/07/05','RR/MM/DD')
, 2300000, 1, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);

INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL,'이유미', 'cleanup200304'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('92/08/06','RR/MM/DD'), 'F'
, '010-3333-3333', TO_DATE('20/03/04','RR/MM/DD'), TO_DATE('22/07/03','RR/MM/DD')
, 'Y', '인사관리자', TO_DATE('22/07/03','RR/MM/DD')
, 3400000, 5, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);

INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL, '신순록', 'cleanup210627'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('94/07/06','RR/MM/DD'), 'M'
, '010-4444-4444', TO_DATE('22/06/27','RR/MM/DD'), NULL
, 'N', '일반관리자', TO_DATE('22/07/05','RR/MM/DD')
, 2500000, 2, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);

INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL, '조완', 'cleanup210728'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('96/04/09','RR/MM/DD'), 'M'
, '010-5555-5555', TO_DATE('21/07/28','RR/MM/DD'), NULL
, 'N', '재정담당자', TO_DATE('22/07/04','RR/MM/DD')
, 4300000, 6, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);

INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL, '이은조', 'cleanup210607'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('95/10/18','RR/MM/DD'), 'F'
, '010-6666-6666', TO_DATE('21/06/07','RR/MM/DD'), TO_DATE('22/07/02','RR/MM/DD')
, 'Y', '보안담당자', TO_DATE('22/07/01','RR/MM/DD')
, 3200000, 7, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);

INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL, '조아영', 'cleanup220613'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('97/11/13','RR/MM/DD'), 'F'
, '010-7777-7777', TO_DATE('22/06/13','RR/MM/DD'), NULL
, 'N', '보안담당자', TO_DATE('22/07/05','RR/MM/DD')
, 1800000, 0, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);


INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL, '이다영', 'cleanup210628'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('94/07/06','RR/MM/DD'), 'M'
, '010-8888-8888', TO_DATE('22/06/27','RR/MM/DD'), NULL
, 'N', '일반관리자', TO_DATE('22/07/05','RR/MM/DD')
, 2500000, 2, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);

INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL, '유호준', 'cleanup210729'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('96/04/09','RR/MM/DD'), 'M'
, '010-9999-9999', TO_DATE('21/07/28','RR/MM/DD'), NULL
, 'N', '재정담당자', TO_DATE('22/07/04','RR/MM/DD')
, 4300000, 6, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);

INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL, '유한조', 'cleanup210608'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('95/10/18','RR/MM/DD'), 'F'
, '010-1111-2222', TO_DATE('21/06/07','RR/MM/DD'), TO_DATE('22/07/02','RR/MM/DD')
, 'Y', '보안담당자', TO_DATE('22/07/01','RR/MM/DD')
, 3200000, 7, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);

INSERT 
  INTO TBL_ADMIN
(
  ADMIN_NO, ADMIN_NAME, ADMIN_ID
, ADMIN_PWD, ADMIN_BIRTH, ADMIN_GENDER
, ADMIN_PHONE, ADMIN_HIRE_DATE, ADMIN_RETIRE_DATE
, ADMIN_RETIRE_YN, ADMIN_JOB, ADMIN_LAST_LOGIN_DATE
, ADMIN_SALARY, ADMIN_USE_ANNUAL_VACATION, ADMIN_EMAIL
, ADMIN_ADDRESS, ADMIN_PICTURE_SAVE_NAME, ADMIN_PICTURE_SAVE_ROOT
, ADMIN_PICTURE_THUMBNAIL_NAME
)
VALUES
(
  SEQ_TBL_ADMIN.NEXTVAL, '나큰솔', 'cleanup220616'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK', TO_DATE('97/11/13','RR/MM/DD'), 'F'
, '010-1111-3333', TO_DATE('22/06/13','RR/MM/DD'), NULL
, 'N', '보안담당자', TO_DATE('22/07/05','RR/MM/DD')
, 1800000, 0, 'toothcoool@gmail.com'
, '333@경기도 안양시 만안구 안양로@안양아파트364', '사진', 'ddddd'
, '사진 dddd'
);

INSERT INTO TBL_SURCHARGE
( 
  SURCHARGE_INSURANCE, SURCHARGE_COMMISSION, SURCHARGE_BONUS
)
VALUES
(
  8, 10, 200000
);

Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (1,'테스트','22072328','$2a$10$LIIlIPPhSuK/3pjmxQxWOeX5MTWqSQZkcEGYdOR2wFneQcIwsetFG',to_date('22/06/28','RR/MM/DD'),'F','010-3242-2342',to_date('22/07/23','RR/MM/DD'),null,0,0,to_date('22/07/23','RR/MM/DD'),'N','Y',to_date('22/07/23','RR/MM/DD'),'Y','Y','Y',to_date('22/07/23','RR/MM/DD'),'N','sref3423@naver.com','11111@기본주소@상세주소1',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (2,'동그라미','22072630','$2a$10$X3l6eEdfEDgQWXDNqd8ae.MRCD.8RCfZoLoLqmjih91qHy5v/sRHC',to_date('96/04/05','RR/MM/DD'),'F','010-2110-3255',null,null,0,0,to_date('22/07/26','RR/MM/DD'),'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'Y','ehdrmfkal1@google.com','05089@서울 광진구 강변북로 2140@210호','1dfbb6f4a6b341be8aac6034550d937e.png','C:\FinalProject\com-project-clean\src\main\webapp\adminEmployeePicture',null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (3,'우병우','22072631','$2a$10$2SLxTLH7YdnlHxDlvSVHuOH67R9E4lHDWGcvPbnUd4A3Q98fEVBvS',to_date('75/12/04','RR/MM/DD'),'F','010-5712-5471',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'Y','knasdo29@naver.com','13355@경기 성남시 중원구 광명로 1@397동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (4,'김벼리','22072632','$2a$10$WcQw.ldnST2GUpuSSDDsye3PmmKO7jUet2w/t5c8MdX/Ha6oz4Gte',to_date('98/05/12','RR/MM/DD'),'F','010-1212-1223',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'Y','starkim@naver.com','11801@경기 의정부시 별꽃길 59@별아파트 101동 1703호',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (5,'바자두','22072633','$2a$10$j8W63GjvERUD3ToSlLSP2OiPS7BYq.RxLuFRkBuTHvnzNYLlZd.6m',to_date('99/05/07','RR/MM/DD'),'F','010-7777-5140',to_date('22/07/26','RR/MM/DD'),null,0,0,null,'N','Y',to_date('22/07/26','RR/MM/DD'),'Y','Y','Y',to_date('22/07/26','RR/MM/DD'),'N','ksdsol292@naver.com','12531@경기 양평군 청운면 다대길 65-6@39동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (6,'이수진','22072634','$2a$10$aove3J0B3QXnHT2TrEzZFOzgkcIdPtLlsJ32k864175arlQID5P5a',to_date('98/05/05','RR/MM/DD'),'F','010-5672-1235',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'Y','suzin01@naver.com','14404@경기 부천시 가로공원로 10@중흥마을아파트 304동 1108호',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (7,'다다도','22072635','$2a$10$j7XA2n1sKbdwV5/e9IKwz.hCf/WxzXQI28QZ6QcifmGkIfabsaj4C',to_date('44/05/07','RR/MM/DD'),'F','010-5712-5171',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'Y','qwoe378@naver.com','37598@경북 포항시 북구 새천년대로 1434@399동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (8,'이안나','22072636','$2a$10$uIumhqOKCHba/ItSWCM3EuZE2G1eXJcsoxmJpIJQFRtQvdVA6/4Cm',to_date('93/02/02','RR/MM/DD'),'F','010-2038-9812',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'Y','dsas14232@google.com','11662@경기 의정부시 가능로 70@809호',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (9,'성성이','22072637','$2a$10$wVLFWT6LpMVC5BcPw2f5F.NEUlJLHpNwGj02PutGpzb6o8AtyiPoG',to_date('92/02/14','RR/MM/DD'),'F','010-5712-5972',to_date('22/07/26','RR/MM/DD'),null,0,0,null,'N','Y',to_date('22/07/26','RR/MM/DD'),'Y','Y','Y',to_date('22/07/26','RR/MM/DD'),'N','askd239@naver.com','05200@서울 강동구 가래여울1길 21@239동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (10,'조은솔','22072638','$2a$10$0QbvzASmYyXpqRljV.XPTeMCNyz0HQFottvT3o7Y6fAUdXy.q01ny',to_date('95/07/28','RR/MM/DD'),'F','010-1233-1344',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'Y','silver01@google.com','12513@경기 양평군 용문면 은고갯길 3@실버오피스텔 1306호',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (11,'나관리','22072639','$2a$10$w9DeQfZb3.2Sy7g6SKXjQ.CwxaPLN.4EV5o8ATmleOtgRHApMAjOq',to_date('93/11/03','RR/MM/DD'),'F','010-2389-4190',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'Y','admin333@naver.com','01012@서울 강북구 4.19로12길 5@블루아파트 1101-502',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (12,'홍홍후','22072641','$2a$10$GRfJNNwV6Cx6iW4pUH6y8ebky.DGBanrxSBcvQqP1TakHYvU9/T82',to_date('92/12/05','RR/MM/DD'),'F','010-214-8755',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'Y','aksdm293@naver.com','59243@전남 강진군 강진읍 강진공단길 8@2023동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (13,'사자바','22072642','$2a$10$TCbaqYp5D/2tH6.TIFHLFurzvtmobU1oxMD4xNc2n9KCj0mCKq73.',to_date('91/08/01','RR/MM/DD'),'F','010-9213-4233',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'Y','sajava@google.com','61447@광주 동구 2순환로 575@동구아파트 502동 1105호',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (14,'유희진','22072643','$2a$10$6x9Q060s0lhlXEzV7yZZ1eyiw1GSIK80ok9cpiD0JESp/9K7CNrRy',to_date('97/08/08','RR/MM/DD'),'F','010-2331-6543',to_date('22/07/26','RR/MM/DD'),null,5,0,null,'Y','Y',to_date('22/07/26','RR/MM/DD'),'Y','Y','Y',to_date('22/07/26','RR/MM/DD'),'N','hee2940@google.com','07530@서울 강서구 강서로 486@602호',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (15,'아난티','22072644','$2a$10$yk5l.tdTbSEdRC2RTPUxBeDRwXkGqqezHrkG/HBPrUGFqaLorpNdK',to_date('92/05/07','RR/MM/DD'),'F','010-1775-5721',to_date('22/07/26','RR/MM/DD'),null,0,0,null,'N','Y',to_date('22/07/26','RR/MM/DD'),'Y','Y','Y',to_date('22/07/26','RR/MM/DD'),'N','skdmk293@naver.com','05200@서울 강동구 가래여울1길 21@23동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (16,'아자바','22072645','$2a$10$smqpL2uHbUkEy4XBzpq2y.gGVBAWMkvarZ76YvmUcnhKbmuw8kBYi',to_date('89/06/13','RR/MM/DD'),'F','010-2389-4555',to_date('22/07/26','RR/MM/DD'),null,0,0,null,'N','Y',to_date('22/07/26','RR/MM/DD'),'Y','Y','Y',to_date('22/07/26','RR/MM/DD'),'N','ajava@naver.com','05695@서울 송파구 가락로6길 3@석촌아파트 502동 1902호',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (17,'임예지','22072646','$2a$10$MliRoOQ4ef0It4.Nxp6.9Ou3furjEZ7sYgZEPJok1FFYypG4m7yMe',to_date('22/07/20','RR/MM/DD'),'F','010-1234-1232',to_date('22/07/26','RR/MM/DD'),null,0,0,null,'N','Y',to_date('22/07/26','RR/MM/DD'),'Y','Y','Y',to_date('22/07/26','RR/MM/DD'),'N','yezi55@naver.com','27875@충북 진천군 덕산읍 예지로 3@예의아파트 501동 ',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (18,'나큰솔','2207262','$2a$10$STuI96elvd8oCZrCH5kg6O2LSzqw/b9FwpQd6aqctKCPsRRZuMdXe',to_date('92/08/19','RR/MM/DD'),'F','010-1234-5678',to_date('22/07/26','RR/MM/DD'),null,0,0,null,'N','Y',to_date('22/07/26','RR/MM/DD'),'Y','Y','Y',to_date('22/07/26','RR/MM/DD'),'N','knsol1992@naver.com','06035@서울 강남구 가로수길 5@14동 1202호',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (19,'가자미','2207263','$2a$10$v6scna4WbaOR3.nY37ds3OwTnBPJsphtoFKB09LF5K5Ogx3HdD5x.',to_date('98/02/12','RR/MM/DD'),'F','010-2359-4332',to_date('22/07/26','RR/MM/DD'),null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','Y','Y',to_date('22/07/26','RR/MM/DD'),'N','gajami5@naver.com','05310@서울 강동구 구천면로42길 4@구천빌딩 807호',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (20,'새우킴','2207264','$2a$10$tlRASCzBcRZUm644rqq3K.kv4bhH6geD9xbspFRpFPTPTHF3vxp1q',to_date('89/07/02','RR/MM/DD'),'F','010-2398-4439',to_date('22/07/26','RR/MM/DD'),null,0,0,to_date('22/07/26','RR/MM/DD'),'N','N',to_date('22/07/26','RR/MM/DD'),'Y','Y','Y',to_date('22/07/26','RR/MM/DD'),'N','kimsaewoo@google.com','08783@서울 관악구 신림로44나길 7@신림빌라 a동 302호',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (21,'김재민','2207265','$2a$10$KFs3mOBadv4AOu7HlrKc7eP4aRi6/M7AyTk9KvhtY9Zw.7H44NIT.',to_date('88/05/04','RR/MM/DD'),'F','010-2593-4312',to_date('22/07/26','RR/MM/DD'),null,5,0,null,'Y','N',to_date('22/07/26','RR/MM/DD'),'Y','Y','Y',to_date('22/07/26','RR/MM/DD'),'N','jaemin55@daum.com','34672@대전 동구 판교3길 3@판교다리 끼고 좌측 3번째 집',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (22,'김상수','2207266','$2a$10$MpIQULaSOuLNikb1iFC6GuLuE.SlAbQDg40j04j2u0xTMkcNSsWQS',to_date('60/12/02','RR/MM/DD'),'F','010-8998-4113',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'N','sangsokim52@daum.com','57638@전남 구례군 구례읍 5일시장작은길 3@구례빌딩 2007호',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (23,'이영록','2207267','$2a$10$1R/SQasb2YB/d0ZQ7puicu.ah8hPnoJEVoS4NVmlK8A3nxswDYfe.',to_date('92/03/05','RR/MM/DD'),'F','010-2349-4431',to_date('22/07/26','RR/MM/DD'),null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','Y','Y',to_date('22/07/26','RR/MM/DD'),'N','youngroks59@daum.com','06253@서울 강남구 강남대로62길 3@강남빌딩 1005호',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (24,'차버그','2207268','$2a$10$qdAbIQNLA42NgKOCekrEjOTJX6y5E6kTgsJkjVvuVwSDNZaXhsTr2',to_date('95/03/04','RR/MM/DD'),'F','010-2349-4344',to_date('22/07/26','RR/MM/DD'),null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','Y','Y',to_date('22/07/26','RR/MM/DD'),'N','bugcha22@google.com','01077@서울 강북구 노해로15길 5@노해하우스 202호',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (25,'공포포','2207269','$2a$10$hc68ff9tG0GAuTDhquqZMeTD.9IgneAlwcdv3E31p7mrfV4olX0X.',to_date('14/06/10','RR/MM/DD'),'F','010-5713-5792',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'N','asdfkmk12134@naver.com','13480@경기 성남시 분당구 대왕판교로 477@124',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (26,'김자바','2207270','$2a$10$gEGO4SmSO.YEJ2xq2mRYQ.oFR5Zx/MZiClAQaq4AiFHjfrMYR3i9m',to_date('77/05/07','RR/MM/DD'),'F','010-2359-4448',to_date('22/07/26','RR/MM/DD'),null,2,0,to_date('22/07/26','RR/MM/DD'),'N','N',to_date('22/07/26','RR/MM/DD'),'Y','Y','Y',to_date('22/07/26','RR/MM/DD'),'N','javakim89@naver.com','05404@서울 강동구 풍성로54길 7@정선빌라 b동 102호',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (27,'자바조아','22072611','$2a$10$bURCfQwkATC/4c5g4WGClep2kZ30s9X8xy685UZuJW5wu472vj5tu',to_date('94/06/09','RR/MM/DD'),'F','010-5221-5379',to_date('22/07/26','RR/MM/DD'),null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','Y','Y',to_date('22/07/26','RR/MM/DD'),'N','knsol1992111@naver.com','63534@제주특별자치도 서귀포시 가가로 14@고렉',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (28,'자바시러','22072612','$2a$10$ZZmzAzPOj8rCJKx/yaPG1eo4GdHR4.njgQX2mBkextGerdUm3SDay',to_date('99/02/05','RR/MM/DD'),'F','010-5372-5557',to_date('22/07/26','RR/MM/DD'),null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','Y','Y',to_date('22/07/26','RR/MM/DD'),'N','owieo18234@naver.com','06035@서울 강남구 가로수길 5@123동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (29,'자바스크','22072613','$2a$10$UFwr/tRiQmQytiK7rGJ92ucWbt03j66yzQ0pXVVkq4EAFkCGyhq1G',to_date('94/05/07','RR/MM/DD'),'F','010-5792-1749',to_date('22/07/26','RR/MM/DD'),null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','Y','Y',to_date('22/07/26','RR/MM/DD'),'N','aksnd29392@naver.com','13480@경기 성남시 분당구 대왕판교로 477@14동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (30,'하하루','22072614','$2a$10$5WXSQLmUVHiawGRk0fRpvOegM/JGzDFgEGAHotWMJDwBdxXxjVtc2',to_date('92/05/17','RR/MM/DD'),'F','010-2172-5327',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'N','asdflkm2328@naver.com','13480@경기 성남시 분당구 대왕판교로 477@20동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (31,'이름','22072615','$2a$10$wGT6g19eEpM3LVWgapg.5.C0Ym2sMRkS20yHJhok.n/eVhC2meZSC',to_date('11/06/07','RR/MM/DD'),'F','010-5781-5413',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'N','knasdo19992@naver.com','06035@서울 강남구 가로수길 5@12동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (32,'도로로','22072616','$2a$10$gbCkMrK1kmiDWPwGtFvhmehTUqrWXkW1oFp3195tJz7ddt1gkQzrC',to_date('25/05/07','RR/MM/DD'),'F','010-2572-5716',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'N','knsdkn12012@naver.com','13480@경기 성남시 분당구 대왕판교로 477@9동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (33,'외다리잭','22072617','$2a$10$hw.8k4bPDjH.X0J4OGZDp.ky2ZzK6rxoDgTltVy61EpSKzcc2ZgwO',to_date('56/02/01','RR/MM/DD'),'F','010-289-5167',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'N','aksdmk2131@naver.com','13355@경기 성남시 중원구 광명로 1@23동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (34,'아아조아','22072618','$2a$10$.lJm//MrxQi8R.nd2GNaButwYiETgM/aW7/oMQqpxvRSo4ypT6JQS',to_date('77/05/08','RR/MM/DD'),'F','010-2475-5111',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'N','asdkm1291@naver.com','63534@제주특별자치도 서귀포시 가가로 14@1220',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (35,'룰루','22072619','$2a$10$foywnYq3nt7A6Hk58uDEc.d/S2iau1/QbVYEmeWjvrFcbLK94DlMu',to_date('87/05/07','RR/MM/DD'),'F','010-2475-5710',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'N','asdk103k@naver.com','08327@서울 구로구 가마산로 77@12동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (36,'마나오링','22072620','$2a$10$ohUaOroIEJKW4HjQIjl7QujOTJ9yeadDJsrCxBRVFGmnW0Tu2e4OG',to_date('55/05/05','RR/MM/DD'),'F','010-7800-5000',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'N','knasdol2992@naver.com','11042@경기 연천군 왕징면 군중로 1222@28동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (37,'내일은','22072621','$2a$10$M91XpWs.M5.d8CyQuEmrVeRibkpgKdN8d0H1MVxnyjvliKnyJ97aO',to_date('77/05/05','RR/MM/DD'),'F','010-5713-5017',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'N','asdfk93@naver.com','06253@서울 강남구 강남대로 298@39동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (38,'아노라','22072622','$2a$10$T2IRRn.XYvY1VdTN9FaHc.LmoK4Q8dlJ.n1XLlqrqQIVTSuEH5Sj.',to_date('25/05/07','RR/MM/DD'),'F','010-5788-5127',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'N','aksdmk2992@naver.com','17609@경기 안성시 서운면 성진로 1243-1@12동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (39,'서파랑','22072623','$2a$10$jdMwG/jpp5VmTxP8LWc.feDfBc4I/gL374zKHj9c9Ccuq5/.NpAo.',to_date('01/06/27','RR/MM/DD'),'F','010-1243-1123',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'N','starkim@naver.com','17099@경기 용인시 기흥구 보라하갈로 57@보라아파트 79동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (40,'김유리','22072624','$2a$10$9a67BjNW5HFtsP.xDXXw/ODlDAGqStdng458BB8tYr8J1R2N2o0ia',to_date('00/07/05','RR/MM/DD'),'F','010-2132-1321',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'N','N','N',to_date('22/07/26','RR/MM/DD'),'Y','rladbfl12@google.com','03055@서울 종로구 북촌로 31-4@201호','ad7e59f09ab7413e84b413139eab2c87.png','C:\FinalProject\com-project-clean\src\main\webapp\adminEmployeePicture',null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (41,'사여우','22072625','$2a$10$xANCiUa9nRkQ1ye4H5QHxeCtAYNwODLhbWXF9AoKC/eqbEF6IUpgC',to_date('76/04/07','RR/MM/DD'),'F','010-2574-5014',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'N','N','N',to_date('22/07/26','RR/MM/DD'),'Y','qwoek293qk@naver.com','11103@경기 포천시 영북면 여우고개로 7@29동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (42,'최가을','22072626','$2a$10$0VJgqcdfWqw3C89ve5ctO.ry0/8eYAUQwL4GHBTsAfgqX2L/Orzqi',to_date('22/07/13','RR/MM/DD'),'F','010-7881-1242',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'N','N','N',to_date('22/07/26','RR/MM/DD'),'Y','kaka445@naver.com','13545@경기 성남시 분당구 고기로 648@포도아파트 501동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (43,'조아영','22072627','$2a$10$5HdMA2JiWpHzb5BrjZVSrOwcUiHwieWsa7QGXu2RGQZ7Z9.LZviYu',to_date('90/05/07','RR/MM/DD'),'F','010-5785-5321',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'N','asdasdk2@naver.com','17965@경기 평택시 포승읍 정문동길 6-6@23동',null,null,null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (44,'박동준','22072628','$2a$10$npJ/IfT0UQmb8Thims9wPOOFRqY/R0X3TXk6o9yL/HFl.VeN9QmWK',to_date('95/07/05','RR/MM/DD'),'F','010-2011-2122',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'Y','N','N',to_date('22/07/26','RR/MM/DD'),'N','ehdwns2@google.com','12035@경기 남양주시 화도읍 가곡로 1@403호','3df4b1c11e2c4ee2a6ea8e7b0903635a.png','C:\FinalProject\com-project-clean\src\main\webapp\adminEmployeePicture',null);
Insert into TBL_EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,EMPLOYEE_ID,EMPLOYEE_PWD,EMPLOYEE_BIRTH,EMPLOYEE_GENDER,EMPLOYEE_PHONE,EMPLOYEE_HIRE_DATE,EMPLOYEE_RETIRE_DATE,EMPLOYEE_SUM_COUNT,EMPLOYEE_SUM_TIME,EMPLOYEE_LAST_LOGIN_DATE,EMPLOYEE_BLACKLIST_YN,EMPLOYEE_RETIRE_YN,REQUEST_DATE,EMPLOYEE_FIRST_CONFIRM_YN,EMPLOYEE_SECOND_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_YN,EMPLOYEE_LAST_CONFIRM_DATE,EMPLOYEE_REGIST_RETURN_YN,EMPLOYEE_EMAIL,EMPLOYEE_ADDRESS,EMPLOYEE_PICTURE_SAVE_NAME,EMPLOYEE_PICTURE_SAVE_ROOT,EMPLOYEE_PICTURE_THUMBNAIL) values (45,'우영우','22072629','$2a$10$vRzP8w7Y3JF2jhvpT0XuFOah7Qw5Z6EmLbo4x68n0jwkF1JvBZY4.',to_date('54/05/07','RR/MM/DD'),'F','010-5741-5700',null,null,0,0,null,'N','N',to_date('22/07/26','RR/MM/DD'),'N','N','N',to_date('22/07/26','RR/MM/DD'),'Y','kn68968@naver.com','31933@충남 서산시 성연면 아남1길 66@98동',null,null,null);


-- "TBL_RESERVATION_INFO";
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (38,'나큰솔','010454587878',8301,'서울 구로구 가마산로23길 10','1층 102호',12,to_date('22/07/26','RR/MM/DD'),'없어요',to_date('22/07/26','RR/MM/DD'),to_timestamp('22/07/26 19:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/07/26 21:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,1,73000,'Y','N','Y','N','Y','Y','N','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (1,'백지영','01012346677',7326,'서울 영등포구 국제금융로 10','103층',12,to_date('22/07/22','RR/MM/DD'),'없습니다!',to_date('22/08/03','RR/MM/DD'),to_timestamp('22/08/03 17:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/03 21:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,0,85000,'N','N','Y','N','Y','N','Y','Y','N');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (2,'권지용','01012346622',7378,'서울 영등포구 가마산로 311','12층 1201호',9,to_date('22/07/22','RR/MM/DD'),'없습니다!',to_date('22/08/03','RR/MM/DD'),to_timestamp('22/08/03 18:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/03 21:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,0,84000,'N','N','Y','N','Y','N','Y','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (3,'빅마마','01012341111',6153,'서울 강남구 봉은사로 404','101호',6,to_date('22/07/22','RR/MM/DD'),'화장실청소 깨끗하게 해줘요',to_date('22/08/03','RR/MM/DD'),to_timestamp('22/08/03 14:30:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/03 17:30:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,1,64000,'Y','N','Y','N','N','N','Y','N','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (4,'아이유','01012341111',18584,'경기 화성시 우정읍 3.1만세로281번길 29-46','101호',6,to_date('22/07/22','RR/MM/DD'),'화장실청소 깨끗하게 해줘요',to_date('22/08/06','RR/MM/DD'),to_timestamp('22/08/06 14:30:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/06 17:30:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,1,84000,'Y','N','Y','N','Y','N','Y','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (5,'박미선','01012341111',7696,'서울 강서구 화곡로33길 4','7층',15,to_date('22/07/22','RR/MM/DD'),'화장실청소 깨끗하게 해줘요',to_date('22/08/06','RR/MM/DD'),to_timestamp('22/08/06 15:30:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/06 19:30:00.000000000','RR/MM/DD HH24:MI:SSXFF'),2,0,160000,'N','N','Y','Y','Y','N','Y','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (6,'임창정','01012341111',1012,'서울 강북구 4.19로12길 5','102호',15,to_date('22/07/22','RR/MM/DD'),'화장실청소 깨끗하게 해줘요',to_date('22/08/06','RR/MM/DD'),to_timestamp('22/08/06 16:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/06 20:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),2,0,140000,'N','N','Y','Y','Y','N','N','N','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (7,'김지영','01012341111',7769,'서울 강서구 강서로17가길 33','102호',5,to_date('22/07/22','RR/MM/DD'),'복층입니다',to_date('22/08/06','RR/MM/DD'),to_timestamp('22/08/06 16:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/06 19:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,0,64000,'N','N','Y','Y','N','N','N','N','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (8,'소지섭','01012346622',1016,'서울 강북구 4.19로17길 14','102호',5,to_date('22/07/22','RR/MM/DD'),'복층입니다',to_date('22/08/03','RR/MM/DD'),to_timestamp('22/08/03 16:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/03 19:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,0,84000,'N','N','Y','Y','Y','N','N','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (9,'이명박','01012341111',5200,'서울 강동구 가래여울길 3','102호',6,to_date('22/07/22','RR/MM/DD'),'복층입니다',to_date('22/07/28','RR/MM/DD'),to_timestamp('22/07/28 09:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/07/28 12:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,1,44000,'Y','N','Y','N','N','N','N','N','N');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (10,'박지호','01012341111',18577,'경기 화성시 팔탄면 3.1만세로798번길 3-4','102호',20,to_date('22/07/22','RR/MM/DD'),'복층입니다',to_date('22/07/28','RR/MM/DD'),to_timestamp('22/07/28 09:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/07/28 13:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),2,2,120000,'Y','N','Y','Y','N','N','N','N','N');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (11,'유한조','01012346622',7363,'서울 영등포구 경인로88길 5-6','102호',20,to_date('22/07/22','RR/MM/DD'),'단골이에요 ~ 잘해주세요',to_date('22/08/03','RR/MM/DD'),to_timestamp('22/08/03 09:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/03 13:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),2,1,130000,'N','N','Y','Y','N','N','N','N','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (12,'최지수','01012341111',1012,'서울 강북구 4.19로12길 5','102호',20,to_date('22/07/22','RR/MM/DD'),'단골이에요 ~ 잘해주세요',to_date('22/08/06','RR/MM/DD'),to_timestamp('22/08/06 09:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/06 13:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),2,1,140000,'N','N','Y','Y','N','N','N','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (13,'강성준','01012341111',1011,'서울 강북구 4.19로 10','102호',13,to_date('22/07/22','RR/MM/DD'),'알아서 잘 해주세요',to_date('22/08/06','RR/MM/DD'),to_timestamp('22/08/06 10:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/06 13:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,1,84000,'Y','N','Y','Y','N','Y','N','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (14,'길성준','01012341111',6250,'서울 강남구 역삼로12길 6','102호',13,to_date('22/07/22','RR/MM/DD'),'알아서 잘 해주세요',to_date('22/08/03','RR/MM/DD'),to_timestamp('22/08/03 10:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/03 13:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,1,84000,'Y','N','Y','Y','N','Y','N','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (15,'박서준','01012346622',31253,'충남 천안시 동남구 병천면 5산단로 357-42','102호',13,to_date('22/07/22','RR/MM/DD'),'잘 부탁드려요',to_date('22/08/03','RR/MM/DD'),to_timestamp('22/08/03 11:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/03 13:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,0,73000,'N','N','Y','Y','N','Y','N','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (16,'김용승','01012344412',6065,'서울 강남구 학동로55길 12','102호',13,to_date('22/07/22','RR/MM/DD'),'잘 부탁드려요',to_date('22/08/06','RR/MM/DD'),to_timestamp('22/08/06 11:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/06 13:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,0,73000,'N','N','Y','Y','N','Y','N','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (17,'나큰솔','01012344412',6143,'서울 강남구 봉은사로44길 1','102호',13,to_date('22/07/22','RR/MM/DD'),'잘 부탁드려요',to_date('22/07/28','RR/MM/DD'),to_timestamp('22/07/28 11:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/07/28 13:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,1,73000,'Y','N','Y','Y','N','Y','N','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (18,'이시원','01012341234',6231,'서울 강남구 도곡로33길 5','102호',12,to_date('22/07/22','RR/MM/DD'),'잘 부탁드려요',to_date('22/07/23','RR/MM/DD'),to_timestamp('22/07/23 18:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/07/23 21:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,1,85000,'Y','N','Y','N','Y','Y','N','Y','N');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (19,'이더워','01077778877',18584,'경기 화성시 우정읍 3.1만세로281번길 29-46','102호',7,to_date('22/07/22','RR/MM/DD'),'잘 부탁드려요',to_date('22/08/03','RR/MM/DD'),to_timestamp('22/08/03 16:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/03 19:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,0,84000,'N','N','Y','N','Y','Y','N','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (20,'너큰솔','01012346622',6230,'서울 강남구 도곡로33길 4','102호',7,to_date('22/07/22','RR/MM/DD'),'잘 부탁드려요',to_date('22/07/28','RR/MM/DD'),to_timestamp('22/07/28 16:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/07/28 19:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,1,84000,'Y','N','Y','N','Y','Y','N','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (21,'서보라','01077778877',1018,'서울 강북구 4.19로32길 69','102호',7,to_date('22/07/22','RR/MM/DD'),'잘 부탁드려요',to_date('22/07/27','RR/MM/DD'),to_timestamp('22/07/27 16:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/07/27 19:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,1,84000,'Y','N','Y','N','Y','Y','N','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (22,'동보라','01034441231',61663,'광주 남구 3.1만세운동길 1','102호',14,to_date('22/07/22','RR/MM/DD'),'잘 부탁드려요',to_date('22/07/27','RR/MM/DD'),to_timestamp('22/07/27 16:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/07/27 19:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,1,84000,'Y','N','Y','N','Y','Y','N','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (23,'최동철','01012346622',44115,'울산 동구 화암10길 4','102호',14,to_date('22/07/22','RR/MM/DD'),'잘 부탁드려요',to_date('22/08/03','RR/MM/DD'),to_timestamp('22/08/03 16:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/03 19:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,0,84000,'N','N','Y','N','Y','Y','N','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (24,'박미소','01034441231',1015,'서울 강북구 4.19로17길 11','102호',16,to_date('22/07/22','RR/MM/DD'),'잘 부탁드려요',to_date('22/08/03','RR/MM/DD'),to_timestamp('22/08/03 17:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/03 21:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),2,0,150000,'N','N','Y','N','Y','Y','N','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (25,'황지상','01034441231',1016,'서울 강북구 4.19로23길 6','102호',12,to_date('22/07/22','RR/MM/DD'),'잘 부탁드려요',to_date('22/07/28','RR/MM/DD'),to_timestamp('22/07/28 13:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/07/28 16:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,1,64000,'Y','N','Y','N','Y','Y','N','N','N');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (26,'구창모','01034441231',61738,'광주 남구 2순환로 1508','63빌딩 12층',12,to_date('22/07/23','RR/MM/DD'),'잘 부탁드려요',to_date('22/07/25','RR/MM/DD'),to_timestamp('22/07/25 17:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/07/25 20:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,1,64000,'Y','N','Y','N','N','Y','N','N','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (27,'이미란','01012341234',5695,'서울 송파구 가락로12길 4','102호',17,to_date('22/07/22','RR/MM/DD'),'단골이에요 ~ 잘해주세요',to_date('22/07/25','RR/MM/DD'),to_timestamp('22/07/25 17:30:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/07/25 21:30:00.000000000','RR/MM/DD HH24:MI:SSXFF'),2,2,140000,'Y','N','Y','N','Y','Y','N','Y','N');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (28,'최소정','01034441231',1012,'서울 강북구 4.19로12길 5','101호',9,to_date('22/07/22','RR/MM/DD'),'알아서 잘 해주세요',to_date('22/07/25','RR/MM/DD'),to_timestamp('22/07/25 18:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/07/25 20:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,1,63000,'Y','N','Y','N','N','Y','N','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (29,'정상수','01012346622',1012,'서울 강북구 4.19로12길 5','108호',9,to_date('22/07/22','RR/MM/DD'),'우리집 더러워요',to_date('22/07/24','RR/MM/DD'),to_timestamp('22/07/24 18:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/07/24 20:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,1,63000,'Y','N','Y','N','N','Y','N','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (30,'최지수','01012341111',1012,'서울 강북구 4.19로12길 5','102호',20,to_date('22/07/22','RR/MM/DD'),'단골이에요 ~ 잘해주세요',to_date('22/08/06','RR/MM/DD'),to_timestamp('22/08/06 09:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/06 13:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),2,0,140000,'N','N','Y','Y','N','N','N','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (37,'호지호','01012312341',3325,'서울 은평구 갈현로23길 1','23호',12,to_date('22/07/26','RR/MM/DD'),'없어요',to_date('22/07/26','RR/MM/DD'),to_timestamp('22/07/26 14:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/07/26 17:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,1,64000,'Y','N','Y','N','Y','N','N','Y','N');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (31,'너지만','01012341234',28574,'충북 청주시 서원구 1순환로 632','102호',14,to_date('22/07/26','RR/MM/DD'),'없어요',to_date('22/08/03','RR/MM/DD'),to_timestamp('22/08/03 12:30:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/03 15:30:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,0,74000,'N','N','Y','N','Y','Y','N','Y','N');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (32,'카지노','01012345999',1012,'서울 강북구 4.19로12길 5','107호',10,to_date('22/07/26','RR/MM/DD'),'깨끗하게 부탁해요',to_date('22/07/27','RR/MM/DD'),to_timestamp('22/07/27 15:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/07/27 18:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,1,74000,'Y','N','Y','N','Y','N','N','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (33,'카지노','01012345999',8864,'서울 관악구 난곡로43길 3-4','107호',17,to_date('22/07/26','RR/MM/DD'),'없어요',to_date('22/07/27','RR/MM/DD'),to_timestamp('22/07/27 15:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/07/27 18:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),2,2,84000,'Y','N','Y','N','Y','N','Y','Y','Y');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (34,'김상준','01099993874',5725,'서울 송파구 동남로 263','102호',8,to_date('22/07/26','RR/MM/DD'),'할게 많습니다.',to_date('22/07/27','RR/MM/DD'),to_timestamp('22/07/27 15:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/07/27 17:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,1,63000,'Y','N','Y','Y','Y','Y','N','N','N');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (35,'김상준','01099993874',61738,'광주 남구 2순환로 1508','102호',8,to_date('22/07/26','RR/MM/DD'),'할게 많습니다.',to_date('22/08/03','RR/MM/DD'),to_timestamp('22/08/03 15:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/08/03 17:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,0,53000,'N','N','Y','Y','N','Y','N','N','N');
Insert into TBL_RESERVATION_INFO (RESERVATION_NO,USER_NAME,USER_PHONE_NO,USER_POSTAL_NO,USER_ADDRESS,USER_DETAIL_ADDRESS,USER_HOUSE_SIZE,USER_RESERVATION_DATE,USER_REQUIREMENTS,BUSINESS_DATE,BUSINESS_START_TIME,BUSINESS_END_TIME,BUSINESS_FIXED_PEOPLE,BUSINESS_APPLY_PEOPLE,TOTAL_PAYMENT,APPLY_END_YN,RESERVATION_CANCEL_YN,PAYMENT_YN,GASHOOD_CLEAN_YN,MOLD_CLEAN_YN,FILTER_CLEAN_YN,WAREHOUSE_CLEAN_YN,PET_YN,MULTIPLE_LAYER_YN) values (36,'나큰솔','01012341234',28787,'충북 청주시 상당구 1순환로 1202-1','1008호',14,to_date('22/07/26','RR/MM/DD'),'없어요',to_date('22/07/25','RR/MM/DD'),to_timestamp('22/07/25 13:30:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/07/25 16:30:00.000000000','RR/MM/DD HH24:MI:SSXFF'),1,1,84000,'Y','N','Y','Y','Y','Y','N','N','Y');

-- TBL_BEST_EMPLOYEE_PAY

INSERT 
   INTO TBL_BEST_EMPLOYEE_PAY
   ( 
   BEST_EMPLOYEE_PAY_HISTORY_NO, BEST_EMPLOYEE_PAY_DATE, BEST_EMPLOYEE_NO, BEST_EMPLOYEE_BONUS
   ) 
   VALUES 
   (
   SEQ_TBL_BEST_EMPLOYEE_PAY.NEXTVAL, TO_DATE('22-02-01', 'YY-MM-DD'), 1, 200000
   );
INSERT 
   INTO TBL_BEST_EMPLOYEE_PAY
   ( 
   BEST_EMPLOYEE_PAY_HISTORY_NO, BEST_EMPLOYEE_PAY_DATE, BEST_EMPLOYEE_NO, BEST_EMPLOYEE_BONUS
   ) 
   VALUES 
   (
   SEQ_TBL_BEST_EMPLOYEE_PAY.NEXTVAL, TO_DATE('22-03-01', 'YY-MM-DD'), 14, 200000
   );
INSERT 
   INTO TBL_BEST_EMPLOYEE_PAY
   ( 
   BEST_EMPLOYEE_PAY_HISTORY_NO, BEST_EMPLOYEE_PAY_DATE, BEST_EMPLOYEE_NO, BEST_EMPLOYEE_BONUS
   ) 
   VALUES 
   (
   SEQ_TBL_BEST_EMPLOYEE_PAY.NEXTVAL, TO_DATE('22-04-01', 'YY-MM-DD'), 14, 200000
   );
INSERT 
   INTO TBL_BEST_EMPLOYEE_PAY
   ( 
   BEST_EMPLOYEE_PAY_HISTORY_NO, BEST_EMPLOYEE_PAY_DATE, BEST_EMPLOYEE_NO, BEST_EMPLOYEE_BONUS
   ) 
   VALUES 
   (
   SEQ_TBL_BEST_EMPLOYEE_PAY.NEXTVAL, TO_DATE('22-05-01', 'YY-MM-DD'), 15, 200000
   );
INSERT 
   INTO TBL_BEST_EMPLOYEE_PAY
   ( 
   BEST_EMPLOYEE_PAY_HISTORY_NO, BEST_EMPLOYEE_PAY_DATE, BEST_EMPLOYEE_NO, BEST_EMPLOYEE_BONUS
   ) 
   VALUES 
   (
   SEQ_TBL_BEST_EMPLOYEE_PAY.NEXTVAL, TO_DATE('22-06-01', 'YY-MM-DD'), 11, 200000
   );

